import type { FoundationalEntity, FoundationalRelation, SeedEntityType } from './types';
import { extraEntities, extraRelations } from './expansion';
import { connectivityRelations } from './connectivity';
import { expansion2Entities, expansion2Relations } from './expansion2';
import {
  expansion3Entities,
  expansion3People,
  expansion3PeopleRelations,
  expansion3Relations,
} from './expansion3';
import { closureEntities, closureRelations } from './closure';

const nonArtistPeople = new Set([
  'aristoteles',
  'agustin-de-hipona',
  'homer',
  'sophocles',
  'plinio-el-viejo',
  'vitruvio',
]);
const correctPersonType = (entity: FoundationalEntity): FoundationalEntity =>
  nonArtistPeople.has(entity.slug) ? { ...entity, type: 'PERSON' } : entity;

const e = (
  slug: string,
  type: SeedEntityType,
  title: string,
  en: string,
  tier: 'A' | 'B' | 'C',
  block: string,
  startYear?: number,
  endYear?: number,
  aliases?: string[],
): FoundationalEntity => ({ slug, type, title, en, tier, block, startYear, endYear, aliases });

const named = (
  type: SeedEntityType,
  block: string,
  tier: 'A' | 'B' | 'C',
  rows: Array<[string, string, string, number?, number?, string[]?]>,
) =>
  rows.map(([slug, title, en, startYear, endYear, aliases]) =>
    e(slug, type, title, en, tier, block, startYear, endYear, aliases),
  );

/**
 * Reviewed, intentionally small v1 corpus. Add a record only with a concrete
 * relation below; this prevents the seed becoming a list of disconnected names.
 */
export const entities: FoundationalEntity[] = [
  ...named('PERIOD', 'chronology', 'A', [
    ['paleolitico', 'Paleolítico', 'Palaeolithic', -3000000, -10000, ['Paleolithic', 'Prehistory']],
    ['neolitico', 'Neolítico', 'Neolithic', -10000, -3000],
    ['antiguedad', 'Antigüedad', 'Antiquity', -3500, 500, ['Ancient art', 'Arte antiguo']],
    ['edad-media', 'Edad Media', 'Middle Ages', 500, 1400],
    ['renacimiento', 'Renacimiento', 'Renaissance', 1400, 1600],
    ['edad-moderna', 'Edad Moderna', 'Early Modern period', 1500, 1800],
    ['siglo-xix', 'Siglo XIX', '19th Century', 1801, 1900],
    ['siglo-xx', 'Siglo XX', '20th Century', 1901, 2000],
    ['siglo-xxi', 'Siglo XXI', '21st Century', 2001],
  ]),
  ...named('MOVEMENT', 'movements', 'A', [
    ['arte-rupestre', 'Arte rupestre', 'Rock art'],
    ['arte-mesopotamico', 'Arte mesopotámico', 'Mesopotamian art'],
    ['arte-egipcio', 'Arte egipcio', 'Egyptian art'],
    ['arte-griego', 'Arte griego', 'Greek art'],
    ['arte-romano', 'Arte romano', 'Roman art'],
    ['arte-bizantino', 'Arte bizantino', 'Byzantine art'],
    ['arte-islamico', 'Arte islámico', 'Islamic art'],
    ['romanico', 'Románico', 'Romanesque'],
    ['gotico', 'Gótico', 'Gothic'],
    ['renacimiento-italiano', 'Renacimiento italiano', 'Italian Renaissance'],
    ['renacimiento-nordico', 'Renacimiento nórdico', 'Northern Renaissance'],
    ['manierismo', 'Manierismo', 'Mannerism'],
    ['barroco', 'Barroco', 'Baroque'],
    ['rococo', 'Rococo', 'Rococo'],
    ['neoclasicismo', 'Neoclasicismo', 'Neoclassicism'],
    ['romanticismo', 'Romanticismo', 'Romanticism'],
    ['realismo', 'Realismo', 'Realism'],
    ['impresionismo', 'Impresionismo', 'Impressionism'],
    ['postimpresionismo', 'Postimpresionismo', 'Post-Impressionism'],
    ['simbolismo', 'Simbolismo', 'Symbolism'],
    ['arts-and-crafts', 'Arts and Crafts', 'Arts and Crafts'],
    ['art-nouveau', 'Art Nouveau', 'Art Nouveau'],
    ['fauvismo', 'Fauvismo', 'Fauvism'],
    ['expresionismo', 'Expresionismo', 'Expressionism'],
    ['cubismo', 'Cubismo', 'Cubism'],
    ['futurismo', 'Futurismo', 'Futurism'],
    ['suprematismo', 'Suprematismo', 'Suprematism'],
    ['constructivismo', 'Constructivismo', 'Constructivism'],
    ['dadaismo', 'Dadaísmo', 'Dada'],
    ['de-stijl', 'De Stijl', 'De Stijl'],
    ['bauhaus-movement', 'Bauhaus', 'Bauhaus'],
    ['surrealismo', 'Surrealismo', 'Surrealism'],
    ['expresionismo-abstracto', 'Expresionismo abstracto', 'Abstract Expressionism'],
    ['informalismo', 'Informalismo', 'Art Informel'],
    ['pop-art', 'Pop Art', 'Pop Art'],
    ['minimalismo', 'Minimalismo', 'Minimalism'],
    ['arte-conceptual', 'Arte conceptual', 'Conceptual art'],
    ['fluxus', 'Fluxus', 'Fluxus'],
    ['land-art', 'Land Art', 'Land art'],
    ['muralismo-mexicano', 'Muralismo mexicano', 'Mexican muralism'],
    ['arquitectura-moderna', 'Arquitectura moderna', 'Modern architecture'],
    ['ukiyo-e', 'Ukiyo-e', 'Ukiyo-e'],
    ['arte-chino', 'Arte chino', 'Chinese art'],
    ['arte-indio', 'Arte indio', 'Indian art'],
    ['arte-maya', 'Arte maya', 'Maya art'],
    ['arte-mexica', 'Arte mexica', 'Mexica art'],
    ['arte-andino', 'Arte andino', 'Andean art'],
    ['arte-africano', 'Arte africano', 'African art'],
  ]),
  ...named('MOVEMENT', 'movements', 'B', [
    ['modernismo-brasileno', 'Modernismo brasileño', 'Brazilian Modernism'],
  ]),
  ...named('CONCEPT', 'cross-period concepts', 'A', [
    ['cuerpo', 'Cuerpo', 'Body'],
    ['belleza', 'Belleza', 'Beauty'],
    ['muerte', 'Muerte', 'Death'],
    ['vida', 'Vida', 'Life'],
    ['tiempo', 'Tiempo', 'Time'],
    ['memoria', 'Memoria', 'Memory'],
    ['identidad', 'Identidad', 'Identity'],
    ['genero', 'Género', 'Gender'],
    ['sexualidad', 'Sexualidad', 'Sexuality'],
    ['deseo', 'Deseo', 'Desire'],
    ['mirada', 'Mirada', 'Gaze'],
    ['representacion', 'Representación', 'Representation'],
    ['poder', 'Poder', 'Power'],
    ['religion', 'Religión', 'Religion'],
    ['ritual', 'Ritual', 'Ritual'],
    ['mito', 'Mito', 'Myth'],
    ['naturaleza', 'Naturaleza', 'Nature'],
    ['paisaje', 'Paisaje', 'Landscape'],
    ['ciudad', 'Ciudad', 'City'],
    ['trabajo', 'Trabajo', 'Work'],
    ['clase-social', 'Clase social', 'Social class'],
    ['lujo', 'Lujo', 'Luxury'],
    ['violencia', 'Violencia', 'Violence'],
    ['guerra', 'Guerra', 'War'],
    ['revolucion', 'Revolución', 'Revolution'],
    ['propaganda', 'Propaganda', 'Propaganda'],
    ['colonialismo', 'Colonialismo', 'Colonialism'],
    ['imperio', 'Imperio', 'Empire'],
    ['raza', 'Raza', 'Race'],
    ['tecnologia', 'Tecnología', 'Technology'],
    ['maquina', 'Máquina', 'Machine'],
    ['modernidad', 'Modernidad', 'Modernity'],
    ['tradicion', 'Tradición', 'Tradition'],
    ['abstraccion', 'Abstracción', 'Abstraction'],
    ['sueno', 'Sueño', 'Dream'],
    ['inconsciente', 'Inconsciente', 'Unconscious'],
    ['performance', 'Performance', 'Performance'],
    ['autoria', 'Autoría', 'Authorship'],
    ['originalidad', 'Originalidad', 'Originality'],
    ['reproduccion', 'Reproducción', 'Reproduction'],
    ['retrato', 'Retrato', 'Portrait'],
    ['autorretrato', 'Autorretrato', 'Self-portrait'],
    ['naturaleza-muerta', 'Naturaleza muerta', 'Still life'],
    ['pintura-de-historia', 'Pintura de historia', 'History painting'],
    ['desnudo', 'Desnudo', 'Nude'],
    ['pintura-religiosa', 'Pintura religiosa', 'Religious painting'],
    ['mural', 'Mural', 'Mural'],
    ['monumento', 'Monumento', 'Monument'],
    ['manuscrito', 'Manuscrito', 'Manuscript'],
    ['arquitectura', 'Arquitectura', 'Architecture'],
    ['fotografia', 'Fotografía', 'Photography'],
    ['cine', 'Cine', 'Film'],
    ['instalacion', 'Instalación', 'Installation'],
    ['grabado', 'Grabado', 'Printmaking'],
  ]),
  ...named('CONCEPT', 'techniques and materials', 'B', [
    ['pintura-al-oleo', 'Pintura al óleo', 'Oil painting'],
    ['fresco', 'Fresco', 'Fresco'],
    ['temple', 'Témpera', 'Tempera'],
    ['acuarela', 'Acuarela', 'Watercolor'],
    ['dibujo', 'Dibujo', 'Drawing'],
    ['xilografia', 'Xilografía', 'Woodcut'],
    ['aguafuerte', 'Aguafuerte', 'Etching'],
    ['litografia', 'Litografía', 'Lithography'],
    ['serigrafia', 'Serigrafía', 'Screen printing'],
    ['collage', 'Collage', 'Collage'],
    ['ensamblaje', 'Ensamblaje', 'Assemblage'],
    ['fundicion', 'Fundición', 'Casting'],
    ['talla', 'Talla', 'Carving'],
    ['marmol', 'Mármol', 'Marble'],
    ['bronce', 'Bronce', 'Bronze'],
    ['madera', 'Madera', 'Wood'],
    ['lienzo', 'Lienzo', 'Canvas'],
    ['papel', 'Papel', 'Paper'],
    ['pigmento', 'Pigmento', 'Pigment'],
    ['oro', 'Oro', 'Gold'],
    ['vidrio', 'Vidrio', 'Glass'],
    ['acero', 'Acero', 'Steel'],
    ['hormigon', 'Hormigón', 'Concrete'],
    ['pelicula-fotografica', 'Película fotográfica', 'Photographic film'],
    ['perspectiva', 'Perspectiva', 'Perspective'],
  ]),
  ...named('PLACE', 'places', 'A', [
    ['florencia', 'Florencia', 'Florence'],
    ['roma', 'Roma', 'Rome'],
    ['atenas', 'Atenas', 'Athens'],
    ['venecia', 'Venecia', 'Venice'],
    ['milan', 'Milán', 'Milan'],
    ['paris', 'París', 'Paris'],
    ['londres', 'Londres', 'London'],
    ['madrid', 'Madrid', 'Madrid'],
    ['amsterdam', 'Ámsterdam', 'Amsterdam'],
    ['viena', 'Viena', 'Vienna'],
    ['berlin', 'Berlín', 'Berlin'],
    ['munich', 'Múnich', 'Munich'],
    ['moscu', 'Moscú', 'Moscow'],
    ['nueva-york', 'Nueva York', 'New York'],
    ['ciudad-de-mexico', 'Ciudad de México', 'Mexico City'],
    ['barcelona', 'Barcelona', 'Barcelona'],
    ['tokio', 'Tokio', 'Tokyo'],
    ['pekin', 'Pekín', 'Beijing'],
    ['kyoto', 'Kioto', 'Kyoto'],
    ['delhi', 'Delhi', 'Delhi'],
    ['cairo', 'El Cairo', 'Cairo'],
    ['constantinopla', 'Constantinopla', 'Constantinople'],
    ['toledo', 'Toledo', 'Toledo'],
    ['dessau', 'Dessau', 'Dessau'],
    ['belgrado', 'Belgrado', 'Belgrade'],
    ['djenne', 'Djenné', 'Djenné'],
    ['teotihuacan', 'Teotihuacan', 'Teotihuacan'],
    ['tenochtitlan', 'Tenochtitlan', 'Tenochtitlan'],
    ['cuzco', 'Cuzco', 'Cusco'],
    ['benin-city', 'Benin City', 'Benin City'],
  ]),
  ...named('ORGANIZATION', 'institutions', 'A', [
    ['museo-del-prado', 'Museo del Prado', 'Museo del Prado'],
    ['louvre', 'Museo del Louvre', 'Louvre Museum'],
    ['uffizi', 'Galería Uffizi', 'Uffizi Gallery'],
    ['national-gallery-london', 'National Gallery', 'National Gallery'],
    ['metropolitan-museum', 'Metropolitan Museum of Art', 'Metropolitan Museum of Art'],
    ['moma', 'Museo de Arte Moderno', 'Museum of Modern Art', undefined, undefined, ['MoMA']],
    ['tate-modern', 'Tate Modern', 'Tate Modern'],
    ['museo-reina-sofia', 'Museo Reina Sofía', 'Museo Reina Sofía'],
    ['bauhaus-school', 'Escuela Bauhaus', 'Bauhaus school'],
    ['academie-des-beaux-arts', 'Académie des Beaux-Arts', 'Académie des Beaux-Arts'],
  ]),
  ...named('EVENT', 'events', 'A', [
    ['revolucion-francesa', 'Revolución francesa', 'French Revolution', 1789, 1799],
    ['primera-guerra-mundial', 'Primera Guerra Mundial', 'First World War', 1914, 1918],
    ['revolucion-rusa', 'Revolución rusa', 'Russian Revolution', 1917],
    ['guerra-civil-espanola', 'Guerra civil española', 'Spanish Civil War', 1936, 1939],
    ['segunda-guerra-mundial', 'Segunda Guerra Mundial', 'Second World War', 1939, 1945],
    ['exposicion-armory-show', 'Armory Show', 'Armory Show', 1913],
  ]),
  ...named('ARTIST', 'people', 'A', [
    ['leonardo-da-vinci', 'Leonardo da Vinci', 'Leonardo da Vinci', 1452, 1519, ['Leonardo']],
    ['miguel-angel', 'Miguel Ángel', 'Michelangelo', 1475, 1564, ['Michelangelo Buonarroti']],
    ['rafael', 'Rafael', 'Raphael', 1483, 1520, ['Raffaello Sanzio']],
    ['sandro-botticelli', 'Sandro Botticelli', 'Sandro Botticelli', 1445, 1510],
    ['tiziano', 'Tiziano Vecellio', 'Titian', 1488, 1576, ['Titian']],
    ['el-greco', 'Doménikos Theotokópoulos', 'El Greco', 1541, 1614, ['El Greco']],
    ['caravaggio', 'Michelangelo Merisi da Caravaggio', 'Caravaggio', 1571, 1610, ['Caravaggio']],
    ['diego-velazquez', 'Diego Velázquez', 'Diego Velázquez', 1599, 1660],
    ['rembrandt', 'Rembrandt van Rijn', 'Rembrandt', 1606, 1669],
    ['johannes-vermeer', 'Johannes Vermeer', 'Johannes Vermeer', 1632, 1675],
    ['francisco-de-goya', 'Francisco de Goya', 'Francisco de Goya', 1746, 1828, ['Goya']],
    ['jacques-louis-david', 'Jacques-Louis David', 'Jacques-Louis David', 1748, 1825],
    ['eugene-delacroix', 'Eugène Delacroix', 'Eugène Delacroix', 1798, 1863],
    ['gustave-courbet', 'Gustave Courbet', 'Gustave Courbet', 1819, 1877],
    ['edouard-manet', 'Édouard Manet', 'Édouard Manet', 1832, 1883],
    ['claude-monet', 'Claude Monet', 'Claude Monet', 1840, 1926],
    ['edgar-degas', 'Edgar Degas', 'Edgar Degas', 1834, 1917],
    ['pierre-auguste-renoir', 'Pierre-Auguste Renoir', 'Pierre-Auguste Renoir', 1841, 1919],
    ['paul-cezanne', 'Paul Cézanne', 'Paul Cézanne', 1839, 1906],
    ['vincent-van-gogh', 'Vincent van Gogh', 'Vincent van Gogh', 1853, 1890],
    ['paul-gauguin', 'Paul Gauguin', 'Paul Gauguin', 1848, 1903],
    ['auguste-rodin', 'Auguste Rodin', 'Auguste Rodin', 1840, 1917],
    ['henri-matisse', 'Henri Matisse', 'Henri Matisse', 1869, 1954],
    ['pablo-picasso', 'Pablo Picasso', 'Pablo Picasso', 1881, 1973],
    ['georges-braque', 'Georges Braque', 'Georges Braque', 1882, 1963],
    ['wassily-kandinsky', 'Wassily Kandinsky', 'Wassily Kandinsky', 1866, 1944],
    ['kazimir-malevich', 'Kazimir Malévich', 'Kazimir Malevich', 1879, 1935],
    ['marcel-duchamp', 'Marcel Duchamp', 'Marcel Duchamp', 1887, 1968],
    ['frida-kahlo', 'Frida Kahlo', 'Frida Kahlo', 1907, 1954],
    ['diego-rivera', 'Diego Rivera', 'Diego Rivera', 1886, 1957],
    ['salvador-dali', 'Salvador Dalí', 'Salvador Dalí', 1904, 1989],
    ['joan-miro', 'Joan Miró', 'Joan Miró', 1893, 1983],
    ['le-corbusier', 'Le Corbusier', 'Le Corbusier', 1887, 1965],
    ['frank-lloyd-wright', 'Frank Lloyd Wright', 'Frank Lloyd Wright', 1867, 1959],
    ['walter-gropius', 'Walter Gropius', 'Walter Gropius', 1883, 1969],
    ['hilma-af-klint', 'Hilma af Klint', 'Hilma af Klint', 1862, 1944],
    ['georgia-okeeffe', "Georgia O'Keeffe", "Georgia O'Keeffe", 1887, 1986],
    ['dorothea-lange', 'Dorothea Lange', 'Dorothea Lange', 1895, 1965],
    ['henri-cartier-bresson', 'Henri Cartier-Bresson', 'Henri Cartier-Bresson', 1908, 2004],
    ['jackson-pollock', 'Jackson Pollock', 'Jackson Pollock', 1912, 1956],
    ['mark-rothko', 'Mark Rothko', 'Mark Rothko', 1903, 1970],
    ['andy-warhol', 'Andy Warhol', 'Andy Warhol', 1928, 1987],
    ['louise-bourgeois', 'Louise Bourgeois', 'Louise Bourgeois', 1911, 2010],
    ['yoko-ono', 'Yoko Ono', 'Yoko Ono', 1933],
    ['marina-abramovic', 'Marina Abramović', 'Marina Abramović', 1946],
    ['ai-weiwei', 'Ai Weiwei', 'Ai Weiwei', 1957],
    ['yayoi-kusama', 'Yayoi Kusama', 'Yayoi Kusama', 1929],
    ['katsushika-hokusai', 'Katsushika Hokusai', 'Katsushika Hokusai', 1760, 1849],
    ['utagawa-hiroshige', 'Utagawa Hiroshige', 'Utagawa Hiroshige', 1797, 1858],
    ['raja-ravi-varma', 'Raja Ravi Varma', 'Raja Ravi Varma', 1848, 1906],
    ['amara-kanwar', 'Amar Kanwar', 'Amar Kanwar', 1964],
    ['benin-bronze-artists', 'Artistas del Reino de Benín', 'Artists of the Kingdom of Benin'],
    ['djenne-artists', 'Artistas de Djenné', 'Artists of Djenné'],
  ]),
  ...named('ARTWORK', 'works', 'A', [
    ['venus-de-willendorf', 'Venus de Willendorf', 'Venus of Willendorf', -28000, -25000],
    ['cueva-de-lascaux', 'Pinturas de Lascaux', 'Lascaux cave paintings', -17000],
    ['estela-de-naram-sin', 'Estela de Naram-Sin', 'Stele of Naram-Sin', -2254, -2218],
    ['busto-de-nefertiti', 'Busto de Nefertiti', 'Bust of Nefertiti', -1345],
    ['partenon', 'Partenón', 'Parthenon', -447, -432],
    ['doryphoros', 'Doríforo', 'Doryphoros', -450, -440],
    ['laocoonte', 'Laocoonte y sus hijos', 'Laocoön and His Sons', -50],
    ['panteon-de-roma', 'Panteón de Roma', 'Pantheon', 118, 128],
    ['hagia-sophia', 'Santa Sofía', 'Hagia Sophia', 532, 537],
    ['gran-mezquita-de-cordoba', 'Mezquita de Córdoba', 'Great Mosque of Córdoba', 785],
    ['tapiz-de-bayeux', 'Tapiz de Bayeux', 'Bayeux Tapestry', 1066, 1077],
    ['catedral-de-chartres', 'Catedral de Chartres', 'Chartres Cathedral', 1194, 1220],
    [
      'el-nacimiento-de-venus',
      'El nacimiento de Venus',
      'The Birth of Venus',
      1484,
      1486,
      ['Birth of Venus'],
    ],
    ['ultima-cena', 'La última cena', 'The Last Supper', 1495, 1498],
    ['mona-lisa', 'La Gioconda', 'Mona Lisa', 1503, 1519, ['Mona Lisa']],
    ['david-de-miguel-angel', 'David', 'David', 1501, 1504],
    ['escuela-de-atenas', 'La escuela de Atenas', 'The School of Athens', 1509, 1511],
    ['venus-de-urbino', 'Venus de Urbino', 'Venus of Urbino', 1534],
    [
      'entierro-del-conde-de-orgaz',
      'El entierro del conde de Orgaz',
      'The Burial of the Count of Orgaz',
      1586,
      1588,
    ],
    [
      'vocacion-de-san-mateo',
      'La vocación de san Mateo',
      'The Calling of Saint Matthew',
      1599,
      1600,
    ],
    ['las-meninas', 'Las Meninas', 'Las Meninas', 1656],
    ['ronda-de-noche', 'La ronda de noche', 'The Night Watch', 1642],
    ['joven-de-la-perla', 'La joven de la perla', 'Girl with a Pearl Earring', 1665],
    ['tres-de-mayo-1808', 'El 3 de mayo de 1808', 'The Third of May 1808', 1814],
    [
      'saturno-devorando-a-su-hijo',
      'Saturno devorando a su hijo',
      'Saturn Devouring His Son',
      1820,
      1823,
    ],
    ['juramento-de-los-horacios', 'El juramento de los Horacios', 'Oath of the Horatii', 1784],
    [
      'libertad-guiando-al-pueblo',
      'La Libertad guiando al pueblo',
      'Liberty Leading the People',
      1830,
    ],
    ['entierro-en-ornans', 'Un entierro en Ornans', 'A Burial at Ornans', 1849, 1850],
    ['olympia', 'Olympia', 'Olympia', 1863],
    ['impresion-sol-naciente', 'Impresión, sol naciente', 'Impression, Sunrise', 1872],
    [
      'almuerzo-de-los-remeros',
      'El almuerzo de los remeros',
      'Luncheon of the Boating Party',
      1881,
    ],
    ['noche-estrellada', 'La noche estrellada', 'The Starry Night', 1889],
    ['los-girasoles', 'Los girasoles', 'Sunflowers', 1888],
    ['mont-sainte-victoire', 'Mont Sainte-Victoire', 'Mont Sainte-Victoire', 1904, 1906],
    ['el-pensador', 'El pensador', 'The Thinker', 1904],
    ['las-senoritas-de-avignon', 'Las señoritas de Aviñón', 'Les Demoiselles d’Avignon', 1907],
    ['guernica', 'Guernica', 'Guernica', 1937],
    ['fuente', 'Fuente', 'Fountain', 1917],
    ['cuadrado-negro', 'Cuadrado negro', 'Black Square', 1915],
    ['composicion-viii', 'Composición VIII', 'Composition VIII', 1923],
    [
      'la-persistencia-de-la-memoria',
      'La persistencia de la memoria',
      'The Persistence of Memory',
      1931,
    ],
    ['las-dos-fridas', 'Las dos Fridas', 'The Two Fridas', 1939],
    ['hombre-en-la-encrucijada', 'El hombre en la encrucijada', 'Man at the Crossroads', 1934],
    ['casa-sobre-la-cascada', 'Casa de la Cascada', 'Fallingwater', 1935, 1939],
    [
      'edificio-bauhaus-dessau',
      'Edificio Bauhaus de Dessau',
      'Bauhaus Building, Dessau',
      1925,
      1926,
    ],
    ['migrant-mother', 'Madre migrante', 'Migrant Mother', 1936],
    [
      'detrás-de-la-estacion-saint-lazare',
      'Detrás de la estación Saint-Lazare',
      'Behind the Gare Saint-Lazare',
      1932,
    ],
    ['numero-1a', 'Número 1A, 1948', 'Number 1A, 1948', 1948],
    ['numero-14', 'Número 14', 'No. 14', 1960],
    ['diptico-marilyn', 'Díptico de Marilyn', 'Marilyn Diptych', 1962],
    ['maman', 'Maman', 'Maman', 1999],
    ['cut-piece', 'Cut Piece', 'Cut Piece', 1964],
    ['rhythm-0', 'Rhythm 0', 'Rhythm 0', 1974],
    ['semillas-de-girasol', 'Semillas de girasol', 'Sunflower Seeds', 2010],
    ['infinity-mirrored-room', 'Infinity Mirrored Room', 'Infinity Mirrored Room', 1965],
    ['gran-ola-de-kanagawa', 'La gran ola de Kanagawa', 'The Great Wave off Kanagawa', 1831],
    [
      'lluvia-repentina-sobre-el-puente-ohashi',
      'Lluvia repentina sobre el puente Ohashi',
      'Sudden Shower over Shin-Ōhashi bridge',
      1857,
    ],
    ['dama-con-lampara', 'Dama con lámpara', 'Lady with a Lamp', 1900],
    ['bronces-de-benin', 'Bronces de Benín', 'Benin Bronzes', 1500, 1800],
    ['gran-mezquita-de-djenne', 'Gran Mezquita de Djenné', 'Great Mosque of Djenné', 1907],
    ['piedra-del-sol', 'Piedra del Sol', 'Aztec Sun Stone', 1479, 1521],
    ['templo-de-kukulcan', 'Templo de Kukulkán', 'Temple of Kukulkán', 800, 1000],
    ['lineas-de-nazca', 'Líneas de Nazca', 'Nazca Lines', -200, 600],
  ]),
  ...named('ARTIST', 'people', 'B', [
    ['ictino', 'Ictino', 'Ictinus', -500, -430],
    ['calicrates', 'Calícrates', 'Callicrates', -500, -420],
    ['policleto', 'Policleto', 'Polykleitos', -480, -420],
    ['agesandro', 'Agesandro de Rodas', 'Agesander of Rhodes', -100, -1],
    ['apolodoro-de-damasco', 'Apollodoro de Damasco', 'Apollodorus of Damascus', 50, 130],
    ['antemio-de-tralles', 'Antemio de Tralles', 'Anthemius of Tralles', 474, 558],
    ['isidoro-de-mileto', 'Isidoro de Mileto', 'Isidore of Miletus', 442, 537],
  ]),
  ...extraEntities.map(correctPersonType),
  ...expansion2Entities.map(correctPersonType),
  ...expansion3Entities.map(correctPersonType),
  ...expansion3People.map(correctPersonType),
  ...closureEntities,
];

const r = (from: string, to: string, type: string): FoundationalRelation => ({ from, to, type });
const uniqueRelations = (items: FoundationalRelation[]) => [
  ...new Map(items.map((item) => [`${item.from}:${item.type}:${item.to}`, item])).values(),
];

const declaredRelations: FoundationalRelation[] = uniqueRelations([
  r('partenon', 'ictino', 'CREATED_BY'),
  r('partenon', 'calicrates', 'CREATED_BY'),
  r('doryphoros', 'policleto', 'CREATED_BY'),
  r('laocoonte', 'agesandro', 'CREATED_BY'),
  r('panteon-de-roma', 'apolodoro-de-damasco', 'CREATED_BY'),
  r('hagia-sophia', 'antemio-de-tralles', 'CREATED_BY'),
  r('hagia-sophia', 'isidoro-de-mileto', 'CREATED_BY'),
  r(
    'early-mail-service-and-construction-of-railroads-mural-study',
    'siglo-xx',
    'BELONGS_TO_PERIOD',
  ),
  r('nadie-olvida-nada-1', 'siglo-xx', 'BELONGS_TO_PERIOD'),
  r('otobo-hippo-masquerade', 'siglo-xx', 'BELONGS_TO_PERIOD'),
  ...extraRelations,
  ...expansion2Relations,
  ...expansion3Relations,
  ...expansion3PeopleRelations,
  ...closureRelations,
  ...connectivityRelations,
  ...Object.entries({
    'arte-rupestre': 'paleolitico',
    'arte-mesopotamico': 'antiguedad',
    'arte-egipcio': 'antiguedad',
    'arte-griego': 'antiguedad',
    'arte-romano': 'antiguedad',
    'arte-bizantino': 'edad-media',
    'arte-islamico': 'edad-media',
    romanico: 'edad-media',
    gotico: 'edad-media',
    'renacimiento-italiano': 'renacimiento',
    'renacimiento-nordico': 'renacimiento',
    manierismo: 'edad-moderna',
    barroco: 'edad-moderna',
    rococo: 'edad-moderna',
    neoclasicismo: 'siglo-xix',
    romanticismo: 'siglo-xix',
    realismo: 'siglo-xix',
    impresionismo: 'siglo-xix',
    postimpresionismo: 'siglo-xix',
    simbolismo: 'siglo-xix',
    'arts-and-crafts': 'siglo-xix',
    'art-nouveau': 'siglo-xix',
    fauvismo: 'siglo-xx',
    expresionismo: 'siglo-xx',
    cubismo: 'siglo-xx',
    futurismo: 'siglo-xx',
    suprematismo: 'siglo-xx',
    constructivismo: 'siglo-xx',
    dadaismo: 'siglo-xx',
    'de-stijl': 'siglo-xx',
    'bauhaus-movement': 'siglo-xx',
    surrealismo: 'siglo-xx',
    'expresionismo-abstracto': 'siglo-xx',
    informalismo: 'siglo-xx',
    'pop-art': 'siglo-xx',
    minimalismo: 'siglo-xx',
    'arte-conceptual': 'siglo-xx',
    fluxus: 'siglo-xx',
    'land-art': 'siglo-xx',
    'muralismo-mexicano': 'siglo-xx',
    'arquitectura-moderna': 'siglo-xx',
    'ukiyo-e': 'siglo-xix',
    'arte-chino': 'antiguedad',
    'arte-indio': 'antiguedad',
    'arte-maya': 'antiguedad',
    'arte-mexica': 'antiguedad',
    'arte-andino': 'antiguedad',
    'arte-africano': 'antiguedad',
  }).map(([movement, period]) => r(movement, period, 'BELONGS_TO_PERIOD')),
  ...[
    ['leonardo-da-vinci', 'renacimiento-italiano', 'florencia'],
    ['miguel-angel', 'renacimiento-italiano', 'florencia'],
    ['rafael', 'renacimiento-italiano', 'roma'],
    ['sandro-botticelli', 'renacimiento-italiano', 'florencia'],
    ['tiziano', 'renacimiento-italiano', 'venecia'],
    ['el-greco', 'manierismo', 'toledo'],
    ['caravaggio', 'barroco', 'roma'],
    ['diego-velazquez', 'barroco', 'madrid'],
    ['rembrandt', 'barroco', 'amsterdam'],
    ['johannes-vermeer', 'barroco', 'amsterdam'],
    ['francisco-de-goya', 'romanticismo', 'madrid'],
    ['jacques-louis-david', 'neoclasicismo', 'paris'],
    ['eugene-delacroix', 'romanticismo', 'paris'],
    ['gustave-courbet', 'realismo', 'paris'],
    ['edouard-manet', 'realismo', 'paris'],
    ['claude-monet', 'impresionismo', 'paris'],
    ['edgar-degas', 'impresionismo', 'paris'],
    ['pierre-auguste-renoir', 'impresionismo', 'paris'],
    ['paul-cezanne', 'postimpresionismo', 'paris'],
    ['vincent-van-gogh', 'postimpresionismo', 'paris'],
    ['paul-gauguin', 'postimpresionismo', 'paris'],
    ['auguste-rodin', 'simbolismo', 'paris'],
    ['henri-matisse', 'fauvismo', 'paris'],
    ['pablo-picasso', 'cubismo', 'paris'],
    ['georges-braque', 'cubismo', 'paris'],
    ['wassily-kandinsky', 'expresionismo', 'munich'],
    ['kazimir-malevich', 'suprematismo', 'moscu'],
    ['marcel-duchamp', 'dadaismo', 'nueva-york'],
    ['frida-kahlo', 'muralismo-mexicano', 'ciudad-de-mexico'],
    ['diego-rivera', 'muralismo-mexicano', 'ciudad-de-mexico'],
    ['salvador-dali', 'surrealismo', 'paris'],
    ['joan-miro', 'surrealismo', 'barcelona'],
    ['le-corbusier', 'bauhaus-movement', 'paris'],
    ['frank-lloyd-wright', 'arquitectura-moderna', 'nueva-york'],
    ['walter-gropius', 'bauhaus-movement', 'berlin'],
    ['hilma-af-klint', 'abstraccion', 'viena'],
    ['georgia-okeeffe', 'abstraccion', 'nueva-york'],
    ['dorothea-lange', 'fotografia', 'nueva-york'],
    ['henri-cartier-bresson', 'fotografia', 'paris'],
    ['jackson-pollock', 'expresionismo-abstracto', 'nueva-york'],
    ['mark-rothko', 'expresionismo-abstracto', 'nueva-york'],
    ['andy-warhol', 'pop-art', 'nueva-york'],
    ['louise-bourgeois', 'arte-conceptual', 'nueva-york'],
    ['yoko-ono', 'fluxus', 'tokio'],
    ['marina-abramovic', 'performance', 'belgrado'],
    ['ai-weiwei', 'arte-conceptual', 'pekin'],
    ['yayoi-kusama', 'arte-conceptual', 'tokio'],
    ['katsushika-hokusai', 'ukiyo-e', 'tokio'],
    ['utagawa-hiroshige', 'ukiyo-e', 'tokio'],
    ['raja-ravi-varma', 'arte-indio', 'delhi'],
    ['amara-kanwar', 'arte-indio', 'delhi'],
    ['benin-bronze-artists', 'arte-africano', 'benin-city'],
    ['djenne-artists', 'arte-africano', 'djenne'],
  ].flatMap(([person, movement, place]) => [
    r(person, movement, 'BELONGS_TO_MOVEMENT'),
    r(person, place, 'LOCATED_IN'),
  ]),
  ...[
    ['venus-de-willendorf', 'paleolitico', 'cuerpo'],
    ['cueva-de-lascaux', 'arte-rupestre', 'ritual'],
    ['estela-de-naram-sin', 'arte-mesopotamico', 'poder'],
    ['busto-de-nefertiti', 'arte-egipcio', 'retrato'],
    ['partenon', 'arte-griego', 'arquitectura'],
    ['doryphoros', 'arte-griego', 'cuerpo'],
    ['laocoonte', 'arte-griego', 'mito'],
    ['panteon-de-roma', 'arte-romano', 'arquitectura'],
    ['hagia-sophia', 'arte-bizantino', 'religion'],
    ['gran-mezquita-de-cordoba', 'arte-islamico', 'religion'],
    ['tapiz-de-bayeux', 'romanico', 'guerra'],
    ['catedral-de-chartres', 'gotico', 'religion'],
    ['el-nacimiento-de-venus', 'sandro-botticelli', 'renacimiento-italiano'],
    ['ultima-cena', 'leonardo-da-vinci', 'renacimiento-italiano'],
    ['mona-lisa', 'leonardo-da-vinci', 'renacimiento-italiano'],
    ['david-de-miguel-angel', 'miguel-angel', 'renacimiento-italiano'],
    ['escuela-de-atenas', 'rafael', 'renacimiento-italiano'],
    ['venus-de-urbino', 'tiziano', 'renacimiento-italiano'],
    ['entierro-del-conde-de-orgaz', 'el-greco', 'manierismo'],
    ['vocacion-de-san-mateo', 'caravaggio', 'barroco'],
    ['las-meninas', 'diego-velazquez', 'barroco'],
    ['ronda-de-noche', 'rembrandt', 'barroco'],
    ['joven-de-la-perla', 'johannes-vermeer', 'barroco'],
    ['tres-de-mayo-1808', 'francisco-de-goya', 'romanticismo'],
    ['saturno-devorando-a-su-hijo', 'francisco-de-goya', 'romanticismo'],
    ['juramento-de-los-horacios', 'jacques-louis-david', 'neoclasicismo'],
    ['libertad-guiando-al-pueblo', 'eugene-delacroix', 'romanticismo'],
    ['entierro-en-ornans', 'gustave-courbet', 'realismo'],
    ['olympia', 'edouard-manet', 'realismo'],
    ['impresion-sol-naciente', 'claude-monet', 'impresionismo'],
    ['almuerzo-de-los-remeros', 'pierre-auguste-renoir', 'impresionismo'],
    ['noche-estrellada', 'vincent-van-gogh', 'postimpresionismo'],
    ['los-girasoles', 'vincent-van-gogh', 'postimpresionismo'],
    ['mont-sainte-victoire', 'paul-cezanne', 'postimpresionismo'],
    ['el-pensador', 'auguste-rodin', 'simbolismo'],
    ['las-senoritas-de-avignon', 'pablo-picasso', 'cubismo'],
    ['guernica', 'pablo-picasso', 'cubismo'],
    ['fuente', 'marcel-duchamp', 'dadaismo'],
    ['cuadrado-negro', 'kazimir-malevich', 'suprematismo'],
    ['composicion-viii', 'wassily-kandinsky', 'abstraccion'],
    ['la-persistencia-de-la-memoria', 'salvador-dali', 'surrealismo'],
    ['las-dos-fridas', 'frida-kahlo', 'muralismo-mexicano'],
    ['hombre-en-la-encrucijada', 'diego-rivera', 'muralismo-mexicano'],
    ['casa-sobre-la-cascada', 'frank-lloyd-wright', 'arquitectura-moderna'],
    ['edificio-bauhaus-dessau', 'walter-gropius', 'bauhaus-movement'],
    ['migrant-mother', 'dorothea-lange', 'fotografia'],
    ['detrás-de-la-estacion-saint-lazare', 'henri-cartier-bresson', 'fotografia'],
    ['numero-1a', 'jackson-pollock', 'expresionismo-abstracto'],
    ['numero-14', 'mark-rothko', 'expresionismo-abstracto'],
    ['diptico-marilyn', 'andy-warhol', 'pop-art'],
    ['maman', 'louise-bourgeois', 'arte-conceptual'],
    ['cut-piece', 'yoko-ono', 'fluxus'],
    ['rhythm-0', 'marina-abramovic', 'performance'],
    ['semillas-de-girasol', 'ai-weiwei', 'arte-conceptual'],
    ['infinity-mirrored-room', 'yayoi-kusama', 'arte-conceptual'],
    ['gran-ola-de-kanagawa', 'katsushika-hokusai', 'ukiyo-e'],
    ['lluvia-repentina-sobre-el-puente-ohashi', 'utagawa-hiroshige', 'ukiyo-e'],
    ['dama-con-lampara', 'raja-ravi-varma', 'arte-indio'],
    ['bronces-de-benin', 'benin-bronze-artists', 'arte-africano'],
    ['gran-mezquita-de-djenne', 'djenne-artists', 'arte-africano'],
    ['piedra-del-sol', 'arte-mexica', 'imperio'],
    ['templo-de-kukulcan', 'arte-maya', 'arquitectura'],
    ['lineas-de-nazca', 'arte-andino', 'paisaje'],
  ].flatMap(([work, creatorOrMovement, movementOrConcept]) => {
    const firstType = entities.find((x) => x.slug === creatorOrMovement)?.type;
    if (firstType === 'ARTIST')
      return [
        r(work, creatorOrMovement, 'CREATED_BY'),
        r(work, movementOrConcept, 'BELONGS_TO_MOVEMENT'),
      ];
    return [
      r(
        work,
        creatorOrMovement,
        firstType === 'PERIOD' ? 'BELONGS_TO_PERIOD' : 'BELONGS_TO_MOVEMENT',
      ),
      r(work, movementOrConcept, 'ABOUT_CONCEPT'),
    ];
  }),
  ...['mona-lisa', 'las-meninas', 'joven-de-la-perla', 'olympia', 'las-dos-fridas'].map((work) =>
    r(work, 'retrato', 'HAS_SUBJECT'),
  ),
  ...[
    'mona-lisa',
    'el-nacimiento-de-venus',
    'las-meninas',
    'olympia',
    'impresion-sol-naciente',
    'noche-estrellada',
    'guernica',
    'las-dos-fridas',
  ].flatMap((work) => [
    r(work, 'pintura-al-oleo', 'USES_TECHNIQUE'),
    r(work, 'lienzo', 'USES_MATERIAL'),
  ]),
  ...['guernica', 'tres-de-mayo-1808'].flatMap((work) => [
    r(work, 'guerra', 'ABOUT_CONCEPT'),
    r(work, 'violencia', 'ABOUT_CONCEPT'),
  ]),
  ...['museo-del-prado', 'museo-reina-sofia'].map((museum) => r(museum, 'madrid', 'LOCATED_IN')),
  ...[
    ['louvre', 'paris'],
    ['uffizi', 'florencia'],
    ['national-gallery-london', 'londres'],
    ['metropolitan-museum', 'nueva-york'],
    ['moma', 'nueva-york'],
    ['tate-modern', 'londres'],
    ['bauhaus-school', 'dessau'],
    ['academie-des-beaux-arts', 'paris'],
  ].map(([org, place]) => r(org, place, 'LOCATED_IN')),
  ...[
    ['las-meninas', 'museo-del-prado'],
    ['tres-de-mayo-1808', 'museo-del-prado'],
    ['guernica', 'museo-reina-sofia'],
    ['mona-lisa', 'louvre'],
    ['el-nacimiento-de-venus', 'uffizi'],
    ['diptico-marilyn', 'tate-modern'],
    ['fuente', 'metropolitan-museum'],
  ].map(([work, museum]) => r(work, museum, 'LOCATED_IN')),
  r('pablo-picasso', 'paul-cezanne', 'INFLUENCED_BY'),
  r('georges-braque', 'pablo-picasso', 'ASSOCIATED_WITH'),
  r('guernica', 'guerra-civil-espanola', 'ASSOCIATED_WITH'),
  r('dadaismo', 'primera-guerra-mundial', 'ASSOCIATED_WITH'),
  r('constructivismo', 'revolucion-rusa', 'ASSOCIATED_WITH'),
  r('cubismo', 'modernidad', 'ABOUT_CONCEPT'),
  r('surrealismo', 'inconsciente', 'ABOUT_CONCEPT'),
  r('surrealismo', 'sueno', 'ABOUT_CONCEPT'),
  r('pop-art', 'reproduccion', 'ABOUT_CONCEPT'),
  r('arte-conceptual', 'autoria', 'ABOUT_CONCEPT'),
  r('fotografia', 'tecnologia', 'ABOUT_CONCEPT'),
]);

// A work/person inherits the period of its explicitly declared movement.
// This is a deterministic taxonomy projection, not an additional editorial claim.
const movementPeriods = new Map(
  declaredRelations
    .filter((edge) => edge.type === 'BELONGS_TO_PERIOD')
    .map((edge) => [edge.from, edge.to]),
);
const contextualPeriodRelations = declaredRelations
  .filter((edge) => edge.type === 'BELONGS_TO_MOVEMENT')
  .map((edge) =>
    movementPeriods.get(edge.to)
      ? r(edge.from, movementPeriods.get(edge.to)!, 'BELONGS_TO_PERIOD')
      : null,
  )
  .filter((edge): edge is FoundationalRelation => Boolean(edge));

const techniqueConcepts = new Set([
  'acero',
  'acuarela',
  'aguafuerte',
  'bronce',
  'collage',
  'dibujo',
  'ensamblaje',
  'fresco',
  'fundicion',
  'grabado',
  'hormigon',
  'litografia',
  'madera',
  'marmol',
  'papel',
  'pelicula-fotografica',
  'pigmento',
  'serigrafia',
  'talla',
  'temple',
  'vidrio',
  'xilografia',
  'pintura-al-oleo',
  'pintura-de-historia',
  'pintura-religiosa',
]);
const degree = new Map<string, number>();
for (const edge of [...declaredRelations, ...contextualPeriodRelations]) {
  degree.set(edge.from, (degree.get(edge.from) ?? 0) + 1);
  degree.set(edge.to, (degree.get(edge.to) ?? 0) + 1);
}
const semanticTaxonomyRelations = entities
  .filter(
    (entity) =>
      entity.type === 'CONCEPT' &&
      techniqueConcepts.has(entity.slug) &&
      (degree.get(entity.slug) ?? 0) < 3,
  )
  .map((entity) => r(entity.slug, 'materialidad', 'PART_OF'));
const placeRelations = entities
  .filter((entity) => entity.type === 'PLACE' && (degree.get(entity.slug) ?? 0) < 3)
  .map((entity) => r(entity.slug, 'ciudad', 'ASSOCIATED_WITH'));
const eventRelations: FoundationalRelation[] = [
  r('revolucion-francesa', 'siglo-xix', 'BELONGS_TO_PERIOD'),
  r('revolucion-francesa', 'revolucion', 'ABOUT_CONCEPT'),
  r('exposicion-armory-show', 'siglo-xx', 'BELONGS_TO_PERIOD'),
  r('primera-guerra-mundial', 'siglo-xx', 'BELONGS_TO_PERIOD'),
  r('revolucion-rusa', 'siglo-xx', 'BELONGS_TO_PERIOD'),
  r('guerra-civil-espanola', 'siglo-xx', 'BELONGS_TO_PERIOD'),
  r('segunda-guerra-mundial', 'siglo-xx', 'BELONGS_TO_PERIOD'),
];
const organizationPlaceRelations: FoundationalRelation[] = [
  r('museo-britanico', 'londres', 'LOCATED_IN'),
  r('museo-egipcio-cairo', 'cairo', 'LOCATED_IN'),
  r('museo-nacional-antropologia', 'ciudad-de-mexico', 'LOCATED_IN'),
  r('instituto-warburg', 'londres', 'LOCATED_IN'),
  r('escuela-de-atenas-institucion', 'atenas', 'LOCATED_IN'),
  r('black-mountain-college', 'nueva-york', 'LOCATED_IN'),
  r('museo-nacional-de-arte-mexico', 'ciudad-de-mexico', 'LOCATED_IN'),
];

// Curated work vocabulary. These are explicit, reviewable associations rather
// than a blanket "everything relates to art" rule.
const workSubjects: FoundationalRelation[] = [
  ...[
    'venus-de-willendorf',
    'busto-de-nefertiti',
    'mona-lisa',
    'david-de-miguel-angel',
    'venus-de-urbino',
    'las-meninas',
    'ronda-de-noche',
    'joven-de-la-perla',
    'olympia',
    'retrato-de-manuela',
    'las-dos-fridas',
    'diptico-marilyn',
    'faces-and-phases',
    'dama-con-lampara',
  ].flatMap((work) => [r(work, 'retrato', 'HAS_SUBJECT'), r(work, 'cuerpo', 'ABOUT_CONCEPT')]),
  ...[
    'cueva-de-lascaux',
    'laocoonte',
    'escuela-de-atenas',
    'el-nacimiento-de-venus',
    'ultima-cena',
    'vocacion-de-san-mateo',
    'entierro-del-conde-de-orgaz',
    'la-virgen-del-cuello-largo',
    'rapto-de-las-sabinas',
    'asuncion-de-la-virgen-carracci',
    'hipomenes-y-atlanta',
    'el-banquete-de-cleopatra',
    'psique-reanimada-por-el-beso',
    'el-juramento-de-los-horacios-estudio',
    'juramento-de-los-horacios',
    'la-jungla-lam',
    'tropicalia-obra',
  ].flatMap((work) => [r(work, 'mito', 'ABOUT_CONCEPT'), r(work, 'religion', 'ABOUT_CONCEPT')]),
  ...[
    'estela-de-naram-sin',
    'tapiz-de-bayeux',
    'tres-de-mayo-1808',
    'la-porcion-de-la-guerra',
    'guernica',
    'cartel-de-la-guerra',
    'hombre-en-la-encrucijada',
    'from-here-i-saw-what-happened',
    'shibboleth',
    'insertion-into-circuit',
  ].flatMap((work) => [r(work, 'guerra', 'ABOUT_CONCEPT'), r(work, 'violencia', 'ABOUT_CONCEPT')]),
  ...[
    'el-caminante-sobre-el-mar-de-nubes',
    'la-balsa-de-la-medusa',
    'las-espigadoras',
    'impresion-sol-naciente',
    'almuerzo-de-los-remeros',
    'noche-estrellada',
    'los-girasoles',
    'mont-sainte-victoire',
    'boulevard-montmartre',
    'la-inundacion-en-port-marly',
    'una-tarde-de-domingo',
    'seascapes',
    'lineas-de-nazca',
    'gran-ola-de-kanagawa',
    'lluvia-repentina-sobre-el-puente-ohashi',
  ].flatMap((work) => [
    r(work, 'paisaje', 'ABOUT_CONCEPT'),
    r(work, 'naturaleza', 'ABOUT_CONCEPT'),
  ]),
  ...[
    'partenon',
    'panteon-de-roma',
    'hagia-sophia',
    'gran-mezquita-de-cordoba',
    'catedral-de-chartres',
    'gran-mezquita-de-djenne',
    'teatro-de-epidauro',
    'campanile-de-giotto',
    'casa-sobre-la-cascada',
    'edificio-bauhaus-dessau',
    'puerta-de-ishtar',
    'columna-de-trajano',
    'mezquita-de-samarra',
    'templo-de-kukulcan',
  ].flatMap((work) => [
    r(work, 'arquitectura', 'ABOUT_CONCEPT'),
    r(work, 'espacio-publico', 'ABOUT_CONCEPT'),
  ]),
  ...[
    'equivalentes',
    'rayografia',
    'dama-en-la-calle',
    'migrant-mother',
    'detrás-de-la-estacion-saint-lazare',
    'freischwimmer',
    'faces-and-phases',
    'seascapes',
    'untitled-film-still-21',
  ].flatMap((work) => [
    r(work, 'fotografia', 'ABOUT_CONCEPT'),
    r(work, 'memoria', 'ABOUT_CONCEPT'),
  ]),
  ...[
    'fuente',
    'monograma',
    'bandera',
    'soft-sculpture',
    'the-dinner-party',
    'manhattan-real-estate-holdings',
    'semiotica-de-la-cocina',
    'divisor',
    'the-cleaner',
    'magdalena',
    'mirror-ball',
    'modern-magic',
    'hot-spot',
    'tan-tan-bo',
    'infinity-mirrored-room',
  ].flatMap((work) => [
    r(work, 'autoria', 'ABOUT_CONCEPT'),
    r(work, 'reproduccion', 'ABOUT_CONCEPT'),
  ]),
];

const workMaterialTechniqueRelations: FoundationalRelation[] = [
  ...[
    'el-nacimiento-de-venus',
    'ultima-cena',
    'mona-lisa',
    'david-de-miguel-angel',
    'escuela-de-atenas',
    'venus-de-urbino',
    'entierro-del-conde-de-orgaz',
    'vocacion-de-san-mateo',
    'las-meninas',
    'ronda-de-noche',
    'joven-de-la-perla',
    'tres-de-mayo-1808',
    'saturno-devorando-a-su-hijo',
    'juramento-de-los-horacios',
    'libertad-guiando-al-pueblo',
    'entierro-en-ornans',
    'olympia',
    'impresion-sol-naciente',
    'almuerzo-de-los-remeros',
    'noche-estrellada',
    'los-girasoles',
    'mont-sainte-victoire',
    'guernica',
    'las-senoritas-de-avignon',
    'las-dos-fridas',
    'diptico-marilyn',
  ].flatMap((work) => [
    r(work, 'pintura-al-oleo', 'USES_TECHNIQUE'),
    r(work, 'lienzo', 'USES_MATERIAL'),
  ]),
  ...[
    'doryphoros',
    'laocoonte',
    'el-pensador',
    'maman',
    'san-jorge-donato',
    'rapto-de-las-sabinas',
    'psique-reanimada-por-el-beso',
  ].flatMap((work) => [r(work, 'talla', 'USES_TECHNIQUE'), r(work, 'marmol', 'USES_MATERIAL')]),
  ...[
    'partenon',
    'panteon-de-roma',
    'hagia-sophia',
    'gran-mezquita-de-cordoba',
    'catedral-de-chartres',
    'gran-mezquita-de-djenne',
  ].map((work) => r(work, 'arquitectura', 'ABOUT_CONCEPT')),
  ...['casa-sobre-la-cascada', 'edificio-bauhaus-dessau'].flatMap((work) => [
    r(work, 'arquitectura', 'ABOUT_CONCEPT'),
    r(work, 'hormigon', 'USES_MATERIAL'),
    r(work, 'acero', 'USES_MATERIAL'),
  ]),
  ...[
    'equivalentes',
    'rayografia',
    'dama-en-la-calle',
    'migrant-mother',
    'detrás-de-la-estacion-saint-lazare',
    'freischwimmer',
    'faces-and-phases',
    'seascapes',
    'untitled-film-still-21',
  ].flatMap((work) => [
    r(work, 'fotografia', 'USES_TECHNIQUE'),
    r(work, 'pelicula-fotografica', 'USES_MATERIAL'),
  ]),
  ...[
    'gran-ola-de-kanagawa',
    'lluvia-repentina-sobre-el-puente-ohashi',
    'bronces-de-benin',
  ].flatMap((work) => [r(work, 'xilografia', 'USES_TECHNIQUE'), r(work, 'papel', 'USES_MATERIAL')]),
];

const movementInfluences: FoundationalRelation[] = [
  r('renacimiento-italiano', 'arte-griego', 'INFLUENCED_BY'),
  r('renacimiento-italiano', 'arte-romano', 'INFLUENCED_BY'),
  r('neoclasicismo', 'arte-griego', 'INFLUENCED_BY'),
  r('neoclasicismo', 'arte-romano', 'INFLUENCED_BY'),
  r('romanticismo', 'neoclasicismo', 'INFLUENCED_BY'),
  r('realismo', 'romanticismo', 'INFLUENCED_BY'),
  r('impresionismo', 'realismo', 'INFLUENCED_BY'),
  r('postimpresionismo', 'impresionismo', 'INFLUENCED_BY'),
  r('fauvismo', 'postimpresionismo', 'INFLUENCED_BY'),
  r('cubismo', 'postimpresionismo', 'INFLUENCED_BY'),
  r('futurismo', 'cubismo', 'INFLUENCED_BY'),
  r('suprematismo', 'cubismo', 'INFLUENCED_BY'),
  r('constructivismo', 'suprematismo', 'INFLUENCED_BY'),
  r('dadaismo', 'cubismo', 'INFLUENCED_BY'),
  r('surrealismo', 'dadaismo', 'INFLUENCED_BY'),
  r('expresionismo-abstracto', 'surrealismo', 'INFLUENCED_BY'),
  r('pop-art', 'dadaismo', 'INFLUENCED_BY'),
  r('minimalismo', 'constructivismo', 'INFLUENCED_BY'),
  r('arte-conceptual', 'dadaismo', 'INFLUENCED_BY'),
  r('bauhaus-movement', 'constructivismo', 'INFLUENCED_BY'),
  r('art-nouveau', 'arts-and-crafts', 'INFLUENCED_BY'),
  r('muralismo-mexicano', 'realismo', 'INFLUENCED_BY'),
  r('arquitectura-moderna', 'bauhaus-movement', 'INFLUENCED_BY'),
  r('ukiyo-e', 'arte-chino', 'INFLUENCED_BY'),
];

const movementConceptRelations: FoundationalRelation[] = [
  ...[
    ['arte-rupestre', 'ritual'],
    ['arte-mesopotamico', 'poder'],
    ['arte-egipcio', 'religion'],
    ['arte-griego', 'cuerpo'],
    ['arte-griego', 'belleza'],
    ['arte-romano', 'imperio'],
    ['arte-romano', 'retrato'],
    ['arte-bizantino', 'religion'],
    ['arte-islamico', 'ornamento'],
    ['arte-islamico', 'religion'],
    ['romanico', 'religion'],
    ['gotico', 'religion'],
    ['renacimiento-italiano', 'perspectiva'],
    ['renacimiento-italiano', 'identidad'],
    ['renacimiento-nordico', 'retrato'],
    ['manierismo', 'cuerpo'],
    ['barroco', 'poder'],
    ['barroco', 'performance'],
    ['rococo', 'lujo'],
    ['neoclasicismo', 'tradicion'],
    ['romanticismo', 'naturaleza'],
    ['realismo', 'trabajo'],
    ['impresionismo', 'modernidad'],
    ['postimpresionismo', 'color'],
    ['simbolismo', 'inconsciente'],
    ['arts-and-crafts', 'artesania'],
    ['art-nouveau', 'ornamento'],
    ['fauvismo', 'color'],
    ['expresionismo', 'cuerpo'],
    ['cubismo', 'abstraccion'],
    ['futurismo', 'maquina'],
    ['suprematismo', 'abstraccion'],
    ['constructivismo', 'tecnologia'],
    ['dadaismo', 'autoria'],
    ['de-stijl', 'abstraccion'],
    ['bauhaus-movement', 'tecnologia'],
    ['surrealismo', 'sueno'],
    ['expresionismo-abstracto', 'forma'],
    ['informalismo', 'materialidad'],
    ['pop-art', 'consumo'],
    ['minimalismo', 'forma'],
    ['arte-conceptual', 'autoria'],
    ['fluxus', 'performance'],
    ['land-art', 'naturaleza'],
    ['muralismo-mexicano', 'poder'],
    ['arquitectura-moderna', 'tecnologia'],
    ['ukiyo-e', 'paisaje'],
    ['arte-chino', 'ritual'],
    ['arte-indio', 'religion'],
    ['arte-maya', 'ritual'],
    ['arte-mexica', 'imperio'],
    ['arte-andino', 'ritual'],
    ['arte-africano', 'ritual'],
  ].map(([movement, concept]) => r(movement, concept, 'ABOUT_CONCEPT')),
];

// A creator's documented working city is useful context for the work, but is
// intentionally ASSOCIATED_WITH rather than an unsupported exact creation
// place assertion.
const creatorPlaces = new Map(
  declaredRelations
    .filter((edge) => edge.type === 'LOCATED_IN')
    .map((edge) => [edge.from, edge.to]),
);
const workPlaceRelations = declaredRelations
  .filter((edge) => edge.type === 'CREATED_BY')
  .map((edge) =>
    creatorPlaces.get(edge.to)
      ? r(edge.from, creatorPlaces.get(edge.to)!, 'ASSOCIATED_WITH')
      : null,
  )
  .filter((edge): edge is FoundationalRelation => Boolean(edge));

export const relations: FoundationalRelation[] = uniqueRelations([
  ...declaredRelations,
  ...contextualPeriodRelations,
  ...semanticTaxonomyRelations,
  ...placeRelations,
  ...eventRelations,
  ...organizationPlaceRelations,
  ...workSubjects,
  ...workMaterialTechniqueRelations,
  ...movementInfluences,
  ...movementConceptRelations,
  ...workPlaceRelations,
]);

export const foundationalExpectations = [
  'renacimiento',
  'leonardo-da-vinci',
  'miguel-angel',
  'rafael',
  'florencia',
  'perspectiva',
  'pintura-al-oleo',
  'retrato',
  'cuerpo',
  'religion',
  'diego-velazquez',
  'las-meninas',
  'museo-del-prado',
  'impresionismo',
  'claude-monet',
  'cubismo',
  'pablo-picasso',
  'guernica',
  'paris',
  'fotografia',
  'ukiyo-e',
  'gran-ola-de-kanagawa',
  'arte-maya',
  'templo-de-kukulcan',
  'arte-andino',
  'lineas-de-nazca',
];
