import type { FoundationalEntity, FoundationalRelation } from './types';

const entity = (
  slug: string,
  type: FoundationalEntity['type'],
  title: string,
  en: string,
  startYear?: number,
  endYear?: number,
  aliases?: string[],
): FoundationalEntity => ({
  slug,
  type,
  title,
  en,
  startYear,
  endYear,
  aliases,
  tier: 'A',
  block: 'mvp-closure',
});

export const closureEntities: FoundationalEntity[] = [
  entity('chicago', 'PLACE', 'Chicago', 'Chicago'),
  entity('edvard-munch', 'ARTIST', 'Edvard Munch', 'Edvard Munch', 1863, 1944, ['Munch']),
  entity('el-grito', 'ARTWORK', 'El grito', 'The Scream', 1893, 1893, ['The Scream', 'Skrik']),
  entity(
    'gian-lorenzo-bernini',
    'ARTIST',
    'Gian Lorenzo Bernini',
    'Gian Lorenzo Bernini',
    1598,
    1680,
    ['Bernini'],
  ),
  entity(
    'extasis-de-santa-teresa',
    'ARTWORK',
    'Éxtasis de santa Teresa',
    'Ecstasy of Saint Teresa',
    1647,
    1652,
    ['Ecstasy of Saint Teresa'],
  ),
  entity('alberto-giacometti', 'ARTIST', 'Alberto Giacometti', 'Alberto Giacometti', 1901, 1966, [
    'Giacometti',
  ]),
  entity('edward-hopper', 'ARTIST', 'Edward Hopper', 'Edward Hopper', 1882, 1967, ['Hopper']),
  entity('nighthawks', 'ARTWORK', 'Nighthawks', 'Nighthawks', 1942, 1942),
  entity(
    'campbells-soup-cans',
    'ARTWORK',
    'Latas de sopa Campbell',
    "Campbell's Soup Cans",
    1962,
    1962,
    ["Campbell's Soup Cans"],
  ),
  entity(
    'la-traicion-de-las-imagenes',
    'ARTWORK',
    'La traición de las imágenes',
    'The Treachery of Images',
    1929,
    1929,
    ['The Treachery of Images', "Ceci n'est pas une pipe"],
  ),
];

const r = (from: string, to: string, type: string): FoundationalRelation => ({ from, to, type });

export const closureRelations: FoundationalRelation[] = [
  r('instituto-de-arte-chicago', 'chicago', 'LOCATED_IN'),
  r('noche-estrellada', 'moma', 'LOCATED_IN'),
  r('panteon-de-roma', 'roma', 'LOCATED_IN'),
  r('edvard-munch', 'expresionismo', 'BELONGS_TO_MOVEMENT'),
  r('edvard-munch', 'simbolismo', 'ASSOCIATED_WITH'),
  r('el-grito', 'edvard-munch', 'CREATED_BY'),
  r('el-grito', 'expresionismo', 'BELONGS_TO_MOVEMENT'),
  r('el-grito', 'cuerpo', 'ABOUT_CONCEPT'),
  r('gian-lorenzo-bernini', 'barroco', 'BELONGS_TO_MOVEMENT'),
  r('gian-lorenzo-bernini', 'roma', 'LOCATED_IN'),
  r('extasis-de-santa-teresa', 'gian-lorenzo-bernini', 'CREATED_BY'),
  r('extasis-de-santa-teresa', 'barroco', 'BELONGS_TO_MOVEMENT'),
  r('extasis-de-santa-teresa', 'religion', 'ABOUT_CONCEPT'),
  r('alberto-giacometti', 'surrealismo', 'ASSOCIATED_WITH'),
  r('alberto-giacometti', 'cuerpo', 'ABOUT_CONCEPT'),
  r('alberto-giacometti', 'paris', 'LOCATED_IN'),
  r('edward-hopper', 'realismo', 'BELONGS_TO_MOVEMENT'),
  r('edward-hopper', 'nueva-york', 'LOCATED_IN'),
  r('nighthawks', 'edward-hopper', 'CREATED_BY'),
  r('nighthawks', 'realismo', 'BELONGS_TO_MOVEMENT'),
  r('nighthawks', 'ciudad', 'ABOUT_CONCEPT'),
  r('nighthawks', 'instituto-de-arte-chicago', 'LOCATED_IN'),
  r('campbells-soup-cans', 'andy-warhol', 'CREATED_BY'),
  r('campbells-soup-cans', 'pop-art', 'BELONGS_TO_MOVEMENT'),
  r('campbells-soup-cans', 'consumo', 'ABOUT_CONCEPT'),
  r('campbells-soup-cans', 'publicidad', 'ABOUT_CONCEPT'),
  r('campbells-soup-cans', 'medios-de-masas', 'ABOUT_CONCEPT'),
  r('campbells-soup-cans', 'moma', 'LOCATED_IN'),
  r('la-traicion-de-las-imagenes', 'rene-magritte', 'CREATED_BY'),
  r('la-traicion-de-las-imagenes', 'surrealismo', 'BELONGS_TO_MOVEMENT'),
  r('la-traicion-de-las-imagenes', 'representacion', 'ABOUT_CONCEPT'),
  r('la-traicion-de-las-imagenes', 'lenguaje', 'ABOUT_CONCEPT'),
  r('luz', 'vocacion-de-san-mateo', 'ABOUT_CONCEPT'),
  r('luz', 'impresion-sol-naciente', 'ABOUT_CONCEPT'),
  r('luz', 'joven-de-la-perla', 'ABOUT_CONCEPT'),
  r('feminismo', 'the-dinner-party', 'ABOUT_CONCEPT'),
  r('feminismo', 'semiotica-de-la-cocina', 'ABOUT_CONCEPT'),
  r('museo', 'museo-del-prado', 'ASSOCIATED_WITH'),
  r('museo', 'louvre', 'ASSOCIATED_WITH'),
  r('museo', 'moma', 'ASSOCIATED_WITH'),
  r('patrimonio', 'bronces-de-benin', 'ABOUT_CONCEPT'),
  r('patrimonio', 'gran-mezquita-de-djenne', 'ABOUT_CONCEPT'),
];
