import type { FoundationalRelation } from './types';

const r = (from: string, to: string, type: string): FoundationalRelation => ({ from, to, type });

const conceptWorks: Record<string, string[]> = {
  acero: ['casa-sobre-la-cascada', 'maman'],
  acuarela: ['gran-ola-de-kanagawa', 'lluvia-repentina-sobre-el-puente-ohashi'],
  aguafuerte: ['tres-de-mayo-1808', 'estela-de-naram-sin'],
  archivo: ['from-here-i-saw-what-happened', 'guernica'],
  autorretrato: ['autorretrato-con-collar-de-espinas', 'las-dos-fridas'],
  belleza: ['el-nacimiento-de-venus', 'mona-lisa'],
  bronce: ['doryphoros', 'bronces-de-benin'],
  cine: ['la-persistencia-de-la-memoria', 'from-here-i-saw-what-happened'],
  ciudad: ['guernica', 'casa-sobre-la-cascada'],
  'clase-social': ['las-meninas', 'migrant-mother'],
  collage: ['las-senoritas-de-avignon', 'fuente'],
  colonialismo: ['el-barco-de-esclavos', 'from-here-i-saw-what-happened'],
  comunidad: ['semillas-de-girasol', 'tropicalia-obra'],
  cuidado: ['las-dos-fridas', 'maman'],
  deseo: ['olympia', 'el-nacimiento-de-venus'],
  desnudo: ['david-de-miguel-angel', 'olympia'],
  diaspora: ['la-jungla-lam', 'from-here-i-saw-what-happened'],
  dibujo: ['mona-lisa', 'composicion-viii'],
  domesticidad: ['joven-de-la-perla', 'las-meninas'],
  ecologia: ['lineas-de-nazca', 'gran-ola-de-kanagawa'],
  educacion: ['escuela-de-atenas', 'edificio-bauhaus-dessau'],
  ensamblaje: ['maman', 'semillas-de-girasol'],
  esclavitud: ['el-barco-de-esclavos', 'from-here-i-saw-what-happened'],
  espectaculo: ['diptico-marilyn', 'las-meninas'],
  exilio: ['la-jungla-lam', 'guernica'],
  fresco: ['ultima-cena', 'hombre-en-la-encrucijada'],
  fundicion: ['david-de-miguel-angel', 'maman'],
  genero: ['las-dos-fridas', 'olympia'],
  grabado: ['tres-de-mayo-1808', 'gran-ola-de-kanagawa'],
  hormigon: ['casa-sobre-la-cascada', 'gran-mezquita-de-djenne'],
  iconografia: ['el-nacimiento-de-venus', 'busto-de-nefertiti'],
  identidad: ['las-dos-fridas', 'autorretrato-con-collar-de-espinas'],
  instalacion: ['maman', 'infinity-mirrored-room'],
  litografia: ['gran-ola-de-kanagawa', 'dama-con-lampara'],
  lujo: ['retrato-de-adele-bloch-bauer', 'palacio-de-versailles'],
  madera: ['gran-mezquita-de-djenne', 'templo-de-kukulcan'],
  manuscrito: ['tapiz-de-bayeux', 'tapiz-de-bayeux'],
  maquina: ['casa-sobre-la-cascada', 'edificio-bauhaus-dessau'],
  marmol: ['david-de-miguel-angel', 'doryphoros'],
  materialidad: ['maman', 'semillas-de-girasol'],
  melancolia: ['noche-estrellada', 'el-pensador'],
  memoria: ['guernica', 'la-persistencia-de-la-memoria'],
  migracion: ['migrant-mother', 'from-here-i-saw-what-happened'],
  mirada: ['olympia', 'las-meninas'],
  monumento: ['maman', 'panteon-de-roma'],
  muerte: ['saturno-devorando-a-su-hijo', 'tres-de-mayo-1808'],
  mural: ['guernica', 'hombre-en-la-encrucijada'],
  naturaleza: ['impresion-sol-naciente', 'noche-estrellada'],
  'naturaleza-muerta': ['mont-sainte-victoire', 'las-senoritas-de-avignon'],
  originalidad: ['fuente', 'obra-de-arte-en-el-tiempo'],
  oro: ['busto-de-nefertiti', 'retrato-de-adele-bloch-bauer'],
  papel: ['gran-ola-de-kanagawa', 'dama-con-lampara'],
  'pelicula-fotografica': ['migrant-mother', 'untitled-film-still-21'],
  perspectiva: ['escuela-de-atenas', 'ultima-cena'],
  'perspectiva-lineal': ['escuela-de-atenas', 'las-meninas'],
  pigmento: ['cueva-de-lascaux', 'busto-de-nefertiti'],
  'pintura-de-historia': ['guernica', 'juramento-de-los-horacios'],
  'pintura-religiosa': ['ultima-cena', 'vocacion-de-san-mateo'],
  propaganda: ['guernica', 'hombre-en-la-encrucijada'],
  raza: ['from-here-i-saw-what-happened', 'migrant-mother'],
  representacion: ['mona-lisa', 'las-meninas'],
  revolucion: ['libertad-guiando-al-pueblo', 'guernica'],
  'revolucion-industrial': ['vapor-y-nubes-de-steam-boat', 'casa-sobre-la-cascada'],
  serigrafia: ['diptico-marilyn', 'semillas-de-girasol'],
  sexualidad: ['olympia', 'venus-de-urbino'],
  sublime: ['vapor-y-nubes-de-steam-boat', 'noche-estrellada'],
  talla: ['david-de-miguel-angel', 'doryphoros'],
  temple: ['busto-de-nefertiti', 'busto-de-nefertiti'],
  tiempo: ['la-persistencia-de-la-memoria', 'saturno-devorando-a-su-hijo'],
  trabajo: ['migrant-mother', 'hombre-en-la-encrucijada'],
  'trabajo-industrial': ['vapor-y-nubes-de-steam-boat', 'edificio-bauhaus-dessau'],
  tradicion: ['gran-ola-de-kanagawa', 'busto-de-nefertiti'],
  vida: ['el-nacimiento-de-venus', 'las-dos-fridas'],
  vidrio: ['catedral-de-chartres', 'gran-mezquita-de-djenne'],
  xilografia: ['gran-ola-de-kanagawa', 'lluvia-repentina-sobre-el-puente-ohashi'],
};

const placeLinks: Array<[string, string]> = [
  ['alejandria', 'arte-griego'],
  ['buenos-aires', 'tarsila-do-amaral'],
  ['cairo', 'arte-egipcio'],
  ['constantinopla', 'arte-bizantino'],
  ['cordoba', 'arte-islamico'],
  ['cuzco', 'arte-andino'],
  ['hanoi', 'arte-chino'],
  ['kyoto', 'ukiyo-e'],
  ['milan', 'art-nouveau'],
  ['mumbai', 'arte-indio'],
  ['praga', 'art-nouveau'],
  ['tenochtitlan', 'arte-mexica'],
  ['teotihuacan', 'arte-mexica'],
  ['toledo-espanol', 'el-greco'],
  ['zurich', 'dadaismo'],
  ['antwerp', 'peter-paul-rubens'],
  ['barcelona', 'joan-miro'],
  ['belgrado', 'marina-abramovic'],
  ['benin-city', 'benin-bronze-artists'],
  ['bruselas', 'rene-magritte'],
  ['dessau', 'bauhaus-school'],
  ['djenne', 'djenne-artists'],
  ['johannesburgo', 'william-kentridge'],
  ['lagos', 'el-anatsui'],
  ['la-habana', 'wifredo-lam'],
  ['munich', 'wassily-kandinsky'],
  ['napoles', 'jose-de-ribera'],
  ['nuremberg', 'albrecht-durer'],
  ['pekin', 'ai-weiwei'],
  ['sao-paulo', 'tarsila-do-amaral'],
  ['toledo', 'el-greco'],
  ['weimar', 'paul-klee'],
];

const institutionLinks: Array<[string, string]> = [
  ['museo-britanico', 'busto-de-nefertiti'],
  ['museo-egipcio-cairo', 'busto-de-nefertiti'],
  ['museo-nacional-antropologia', 'piedra-del-sol'],
  ['instituto-warburg', 'iconografia'],
  ['escuela-de-atenas-institucion', 'escuela-de-atenas'],
  ['black-mountain-college', 'arte-conceptual'],
  ['instituto-de-arte-chicago', 'noche-estrellada'],
  ['museo-nacional-de-arte-mexico', 'abaporu'],
  ['moma', 'fuente'],
  ['national-gallery-london', 'joven-de-la-perla'],
  ['bauhaus-school', 'edificio-bauhaus-dessau'],
  ['academie-des-beaux-arts', 'juramento-de-los-horacios'],
];

const remainingHubs: FoundationalRelation[] = [
  r('agustin-de-hipona', 'religion', 'ABOUT_CONCEPT'),
  r('agustin-de-hipona', 'roma', 'LOCATED_IN'),
  r('aristoteles', 'arte-griego', 'BELONGS_TO_MOVEMENT'),
  r('aristoteles', 'representacion', 'ABOUT_CONCEPT'),
  r('oswald-de-andrade', 'modernidad', 'ABOUT_CONCEPT'),
  r('oswald-de-andrade', 'sao-paulo', 'LOCATED_IN'),
  r('plinio-el-viejo', 'arte-romano', 'BELONGS_TO_MOVEMENT'),
  r('plinio-el-viejo', 'roma', 'LOCATED_IN'),
  r('arte-performance', 'siglo-xx', 'BELONGS_TO_PERIOD'),
  r('arte-performance', 'performance', 'ABOUT_CONCEPT'),
  r('fotografia-moderna', 'siglo-xx', 'BELONGS_TO_PERIOD'),
  r('fotografia-moderna', 'tecnologia', 'ABOUT_CONCEPT'),
  r('arte-rupestre', 'neolitico', 'BELONGS_TO_PERIOD'),
  r('semillas-de-girasol', 'siglo-xxi', 'BELONGS_TO_PERIOD'),
  r('exposicion-armory-show', 'cubismo', 'ASSOCIATED_WITH'),
  r('exposicion-armory-show', 'modernidad', 'ABOUT_CONCEPT'),
  r('revolucion-francesa', 'neoclasicismo', 'ASSOCIATED_WITH'),
  r('revolucion-francesa', 'poder', 'ABOUT_CONCEPT'),
  r('segunda-guerra-mundial', 'guerra', 'ABOUT_CONCEPT'),
  r('segunda-guerra-mundial', 'propaganda', 'ABOUT_CONCEPT'),
];

const unique = (relations: FoundationalRelation[]) => [
  ...new Map(relations.map((edge) => [`${edge.from}:${edge.type}:${edge.to}`, edge])).values(),
];

export const connectivityRelations: FoundationalRelation[] = unique([
  ...Object.entries(conceptWorks).flatMap(([concept, works]) =>
    works.map((work) => r(work, concept, 'ABOUT_CONCEPT')),
  ),
  ...placeLinks.map(([place, entity]) => r(entity, place, 'LOCATED_IN')),
  ...institutionLinks.map(([institution, entity]) => r(entity, institution, 'LOCATED_IN')),
  ...remainingHubs,
]);
