import type { FoundationalEntity, FoundationalRelation } from './types';

export type EditorialTier = 'A' | 'B' | 'C';

// Tier A is an editorial judgement: canonical entry points across periods,
// geographies and disciplines. It is deliberately not derived from raw degree.
export const tierA = new Set([
  'leonardo-da-vinci',
  'miguel-angel',
  'rafael',
  'sandro-botticelli',
  'tiziano',
  'el-greco',
  'caravaggio',
  'diego-velazquez',
  'rembrandt',
  'johannes-vermeer',
  'francisco-de-goya',
  'jacques-louis-david',
  'eugene-delacroix',
  'jmw-turner',
  'claude-monet',
  'edouard-manet',
  'edgar-degas',
  'paul-cezanne',
  'vincent-van-gogh',
  'auguste-rodin',
  'henri-matisse',
  'pablo-picasso',
  'marcel-duchamp',
  'salvador-dali',
  'frida-kahlo',
  'katsushika-hokusai',
  'le-corbusier',
  'frank-lloyd-wright',
  'andy-warhol',
  'jackson-pollock',
  'mark-rothko',
  'georgia-okeeffe',
  'ai-weiwei',
  'yayoi-kusama',
  'marina-abramovic',
  'cindy-sherman',
  'edvard-munch',
  'gian-lorenzo-bernini',
  'alberto-giacometti',
  'edward-hopper',
  'venus-de-willendorf',
  'cueva-de-lascaux',
  'busto-de-nefertiti',
  'partenon',
  'doryphoros',
  'hagia-sophia',
  'gran-mezquita-de-cordoba',
  'tapiz-de-bayeux',
  'catedral-de-chartres',
  'el-nacimiento-de-venus',
  'ultima-cena',
  'mona-lisa',
  'david-de-miguel-angel',
  'escuela-de-atenas',
  'vocacion-de-san-mateo',
  'las-meninas',
  'ronda-de-noche',
  'joven-de-la-perla',
  'tres-de-mayo-1808',
  'saturno-devorando-a-su-hijo',
  'libertad-guiando-al-pueblo',
  'olympia',
  'impresion-sol-naciente',
  'noche-estrellada',
  'los-girasoles',
  'las-senoritas-de-avignon',
  'guernica',
  'fuente',
  'cuadrado-negro',
  'la-persistencia-de-la-memoria',
  'las-dos-fridas',
  'casa-sobre-la-cascada',
  'edificio-bauhaus-dessau',
  'migrant-mother',
  'diptico-marilyn',
  'maman',
  'cut-piece',
  'gran-ola-de-kanagawa',
  'bronces-de-benin',
  'piedra-del-sol',
  'templo-de-kukulcan',
  'lineas-de-nazca',
  'el-grito',
  'extasis-de-santa-teresa',
  'nighthawks',
  'campbells-soup-cans',
  'la-traicion-de-las-imagenes',
  'renacimiento',
  'renacimiento-italiano',
  'barroco',
  'neoclasicismo',
  'romanticismo',
  'impresionismo',
  'postimpresionismo',
  'expresionismo',
  'cubismo',
  'dadaismo',
  'bauhaus-movement',
  'surrealismo',
  'expresionismo-abstracto',
  'pop-art',
  'minimalismo',
  'arte-conceptual',
  'ukiyo-e',
  'arte-islamico',
  'arte-africano',
  'arte-maya',
  'cuerpo',
  'muerte',
  'memoria',
  'representacion',
  'poder',
  'religion',
  'guerra',
  'colonialismo',
  'paisaje',
  'retrato',
  'fotografia',
  'arquitectura',
  'paris',
  'florencia',
  'roma',
  'madrid',
  'nueva-york',
  'museo-del-prado',
  'louvre',
  'moma',
  'uffizi',
]);

export function tierFor(entity: FoundationalEntity, degree: number): EditorialTier {
  if (tierA.has(entity.slug)) return 'A';
  if (entity.type === 'MOVEMENT' || entity.type === 'PERIOD') return 'B';
  if ((entity.type === 'ARTIST' || entity.type === 'PERSON') && degree >= 4) return 'B';
  if (entity.type === 'ARTWORK' && degree >= 6) return 'B';
  if (entity.type === 'PLACE' && degree >= 4) return 'B';
  if (entity.type === 'ORGANIZATION' && degree >= 2) return 'B';
  if (entity.type === 'EVENT' && degree >= 3) return 'B';
  if (entity.type === 'CONCEPT' && degree >= 4) return 'B';
  return 'C';
}

export function editorialInventory(
  entities: FoundationalEntity[],
  relations: FoundationalRelation[],
) {
  const degree = new Map(entities.map((entity) => [entity.slug, 0]));
  for (const relation of relations) {
    degree.set(relation.from, (degree.get(relation.from) ?? 0) + 1);
    degree.set(relation.to, (degree.get(relation.to) ?? 0) + 1);
  }
  return entities.map((entity) => ({
    ...entity,
    degree: degree.get(entity.slug) ?? 0,
    editorialTier: tierFor(entity, degree.get(entity.slug) ?? 0),
  }));
}
