import type { FoundationalEntity, FoundationalRelation } from './types';

const e = (
  slug: string,
  type: FoundationalEntity['type'],
  title: string,
  en: string,
  block: string,
  startYear?: number,
  endYear?: number,
  aliases?: string[],
): FoundationalEntity => ({ slug, type, title, en, block, tier: 'B', startYear, endYear, aliases });
const rel = (from: string, to: string, type: string): FoundationalRelation => ({ from, to, type });

const people: Array<[string, string, string, string, string, number?, number?]> = [
  ['homer', 'Homero', 'Homer', 'arte-griego', 'atenas', -800, -700],
  ['sophocles', 'Sófocles', 'Sophocles', 'arte-griego', 'atenas', -496, -406],
  ['vitruvio', 'Vitruvio', 'Vitruvius', 'arte-romano', 'roma', -80, -15],
  ['dionisio', 'Dionisio', 'Dionysius', 'arte-bizantino', 'constantinopla', 500, 600],
  [
    'vassily-vereshchagin',
    'Vasily Vereshchagin',
    'Vasily Vereshchagin',
    'realismo',
    'madrid',
    1842,
    1904,
  ],
  ['masaccio', 'Masaccio', 'Masaccio', 'renacimiento-italiano', 'florencia', 1401, 1428],
  ['donatello', 'Donatello', 'Donatello', 'renacimiento-italiano', 'florencia', 1386, 1466],
  [
    'fra-angelico',
    'Fra Angelico',
    'Fra Angelico',
    'renacimiento-italiano',
    'florencia',
    1395,
    1455,
  ],
  [
    'piero-della-francesca',
    'Piero della Francesca',
    'Piero della Francesca',
    'renacimiento-italiano',
    'florencia',
    1415,
    1492,
  ],
  [
    'andrea-mantegna',
    'Andrea Mantegna',
    'Andrea Mantegna',
    'renacimiento-italiano',
    'mantua',
    1431,
    1506,
  ],
  ['giorgione', 'Giorgione', 'Giorgione', 'renacimiento-italiano', 'venecia', 1477, 1510],
  ['pontormo', 'Pontormo', 'Pontormo', 'manierismo', 'florencia', 1494, 1557],
  ['giambologna', 'Giambologna', 'Giambologna', 'manierismo', 'florencia', 1529, 1608],
  ['annibale-carracci', 'Annibale Carracci', 'Annibale Carracci', 'barroco', 'roma', 1560, 1609],
  ['guido-reni', 'Guido Reni', 'Guido Reni', 'barroco', 'roma', 1575, 1642],
  ['frans-hals', 'Frans Hals', 'Frans Hals', 'barroco', 'amsterdam', 1582, 1666],
  [
    'georges-de-la-tour',
    'Georges de La Tour',
    'Georges de La Tour',
    'barroco',
    'paris',
    1593,
    1652,
  ],
  ['antonie-watteau', 'Antoine Watteau', 'Antoine Watteau', 'rococo', 'paris', 1684, 1721],
  ['francois-boucher', 'François Boucher', 'François Boucher', 'rococo', 'paris', 1703, 1770],
  [
    'jean-honore-fragonard',
    'Jean-Honoré Fragonard',
    'Jean-Honoré Fragonard',
    'rococo',
    'paris',
    1732,
    1806,
  ],
  [
    'angelica-kauffmann',
    'Angelica Kauffmann',
    'Angelica Kauffman',
    'neoclasicismo',
    'roma',
    1741,
    1807,
  ],
  ['antonio-canova', 'Antonio Canova', 'Antonio Canova', 'neoclasicismo', 'roma', 1757, 1822],
  [
    'theodore-gericault',
    'Théodore Géricault',
    'Théodore Géricault',
    'romanticismo',
    'paris',
    1791,
    1824,
  ],
  [
    'caspar-david-friedrich',
    'Caspar David Friedrich',
    'Caspar David Friedrich',
    'romanticismo',
    'berlin',
    1774,
    1840,
  ],
  ['honore-daumier', 'Honoré Daumier', 'Honoré Daumier', 'realismo', 'paris', 1808, 1879],
  [
    'jean-francois-millet',
    'Jean-François Millet',
    'Jean-François Millet',
    'realismo',
    'paris',
    1814,
    1875,
  ],
  ['gustave-moreau', 'Gustave Moreau', 'Gustave Moreau', 'simbolismo', 'paris', 1826, 1898],
  [
    'camille-pissarro',
    'Camille Pissarro',
    'Camille Pissarro',
    'impresionismo',
    'paris',
    1830,
    1903,
  ],
  ['alfred-sisley', 'Alfred Sisley', 'Alfred Sisley', 'impresionismo', 'paris', 1839, 1899],
  ['georges-seurat', 'Georges Seurat', 'Georges Seurat', 'postimpresionismo', 'paris', 1859, 1891],
  [
    'toulouse-lautrec',
    'Henri de Toulouse-Lautrec',
    'Henri de Toulouse-Lautrec',
    'postimpresionismo',
    'paris',
    1864,
    1901,
  ],
  ['emile-bernard', 'Émile Bernard', 'Émile Bernard', 'postimpresionismo', 'paris', 1868, 1941],
  [
    'alfred-stieglitz',
    'Alfred Stieglitz',
    'Alfred Stieglitz',
    'fotografia-moderna',
    'nueva-york',
    1864,
    1946,
  ],
  ['man-ray', 'Man Ray', 'Man Ray', 'dadaismo', 'paris', 1890, 1976],
  ['francis-picabia', 'Francis Picabia', 'Francis Picabia', 'dadaismo', 'paris', 1879, 1953],
  ['tristan-tzara', 'Tristan Tzara', 'Tristan Tzara', 'dadaismo', 'zurich', 1896, 1963],
  [
    'sophie-taeuber-arp',
    'Sophie Taeuber-Arp',
    'Sophie Taeuber-Arp',
    'dadaismo',
    'zurich',
    1889,
    1943,
  ],
  ['robert-delaunay', 'Robert Delaunay', 'Robert Delaunay', 'orfismo', 'paris', 1885, 1941],
  ['liubov-popova', 'Liubov Popova', 'Liubov Popova', 'constructivismo', 'moscu', 1889, 1924],
  ['elena-guro', 'Elena Guro', 'Elena Guro', 'futurismo', 'moscu', 1877, 1913],
  [
    'natalia-goncharova',
    'Natalia Goncharova',
    'Natalia Goncharova',
    'futurismo',
    'moscu',
    1881,
    1962,
  ],
  [
    'lyonel-feininger',
    'Lyonel Feininger',
    'Lyonel Feininger',
    'bauhaus-movement',
    'weimar',
    1871,
    1956,
  ],
  ['josef-albers', 'Josef Albers', 'Josef Albers', 'bauhaus-movement', 'weimar', 1888, 1976],
  [
    'laszlo-moholy-nagy',
    'László Moholy-Nagy',
    'László Moholy-Nagy',
    'bauhaus-movement',
    'berlin',
    1895,
    1946,
  ],
  [
    'oskar-schlemmer',
    'Oskar Schlemmer',
    'Oskar Schlemmer',
    'bauhaus-movement',
    'weimar',
    1888,
    1943,
  ],
  [
    'manuela-ballester',
    'Manuela Ballester',
    'Manuela Ballester',
    'muralismo-mexicano',
    'ciudad-de-mexico',
    1908,
    1994,
  ],
  ['alice-neel', 'Alice Neel', 'Alice Neel', 'realismo', 'nueva-york', 1900, 1984],
  ['ben-shahn', 'Ben Shahn', 'Ben Shahn', 'realismo', 'nueva-york', 1898, 1969],
  [
    'philip-guston',
    'Philip Guston',
    'Philip Guston',
    'expresionismo-abstracto',
    'nueva-york',
    1913,
    1980,
  ],
  [
    'lee-krasner',
    'Lee Krasner',
    'Lee Krasner',
    'expresionismo-abstracto',
    'nueva-york',
    1908,
    1984,
  ],
  [
    'helen-frankenthaler',
    'Helen Frankenthaler',
    'Helen Frankenthaler',
    'expresionismo-abstracto',
    'nueva-york',
    1928,
    2011,
  ],
  ['cy-twombly', 'Cy Twombly', 'Cy Twombly', 'expresionismo-abstracto', 'roma', 1928, 2011],
  [
    'robert-rauschenberg',
    'Robert Rauschenberg',
    'Robert Rauschenberg',
    'pop-art',
    'nueva-york',
    1925,
    2008,
  ],
  ['jasper-johns', 'Jasper Johns', 'Jasper Johns', 'pop-art', 'nueva-york', 1930],
  ['claes-oldenburg', 'Claes Oldenburg', 'Claes Oldenburg', 'pop-art', 'nueva-york', 1929, 2022],
  ['bridget-riley', 'Bridget Riley', 'Bridget Riley', 'minimalismo', 'londres', 1931],
  ['richard-serra', 'Richard Serra', 'Richard Serra', 'minimalismo', 'nueva-york', 1938, 2024],
  ['robert-morris', 'Robert Morris', 'Robert Morris', 'minimalismo', 'nueva-york', 1931, 2018],
  ['dan-flavin', 'Dan Flavin', 'Dan Flavin', 'minimalismo', 'nueva-york', 1933, 1996],
  ['judy-chicago', 'Judy Chicago', 'Judy Chicago', 'arte-conceptual', 'nueva-york', 1939],
  ['hans-haacke', 'Hans Haacke', 'Hans Haacke', 'arte-conceptual', 'nueva-york', 1936],
  ['martha-rosler', 'Martha Rosler', 'Martha Rosler', 'arte-conceptual', 'nueva-york', 1943],
  [
    'guillermo-kuitca',
    'Guillermo Kuitca',
    'Guillermo Kuitca',
    'arte-conceptual',
    'buenos-aires',
    1961,
  ],
  [
    'carlos-cruz-diez',
    'Carlos Cruz-Diez',
    'Carlos Cruz-Diez',
    'arte-conceptual',
    'paris',
    1923,
    2019,
  ],
  ['lygia-clark', 'Lygia Clark', 'Lygia Clark', 'arte-conceptual', 'sao-paulo', 1920, 1988],
  ['lygia-pape', 'Lygia Pape', 'Lygia Pape', 'arte-conceptual', 'sao-paulo', 1927, 2004],
  ['cildo-meireles', 'Cildo Meireles', 'Cildo Meireles', 'arte-conceptual', 'sao-paulo', 1948],
  ['beatriz-gonzalez', 'Beatriz González', 'Beatriz González', 'arte-conceptual', 'bogota', 1938],
  ['oscar-murillo', 'Óscar Murillo', 'Óscar Murillo', 'arte-conceptual', 'bogota', 1986],
  ['marlene-dumas', 'Marlene Dumas', 'Marlene Dumas', 'arte-conceptual', 'amsterdam', 1953],
  [
    'wolfgang-tillmans',
    'Wolfgang Tillmans',
    'Wolfgang Tillmans',
    'fotografia-moderna',
    'berlin',
    1968,
  ],
  ['sophie-calle', 'Sophie Calle', 'Sophie Calle', 'arte-conceptual', 'paris', 1953],
  ['walid-beshty', 'Walid Beshty', 'Walid Beshty', 'arte-conceptual', 'nueva-york', 1976],
  ['do-ho-suh', 'Do Ho Suh', 'Do Ho Suh', 'arte-conceptual', 'tokio', 1962],
  [
    'monir-shahroudy-farmanfarmaian',
    'Monir Shahroudy Farmanfarmaian',
    'Monir Shahroudy Farmanfarmaian',
    'arte-conceptual',
    'teheran',
    1924,
    2019,
  ],
  ['geta-bratescu', 'Geta Brătescu', 'Geta Brătescu', 'arte-conceptual', 'bucarest', 1926, 2018],
  ['zanele-muholi', 'Zanele Muholi', 'Zanele Muholi', 'fotografia-moderna', 'johannesburgo', 1972],
  ['ibrahim-el-salahi', 'Ibrahim el-Salahi', 'Ibrahim el-Salahi', 'arte-africano', 'cairo', 1930],
  ['romuald-hazoume', 'Romuald Hazoumè', 'Romuald Hazoumè', 'arte-africano', 'benin-city', 1962],
  [
    'sokari-douglas-camp',
    'Sokari Douglas Camp',
    'Sokari Douglas Camp',
    'arte-africano',
    'lagos',
    1958,
  ],
  ['henrike-naumann', 'Henrike Naumann', 'Henrike Naumann', 'arte-conceptual', 'berlin', 1984],
  ['mona-hatoum', 'Mona Hatoum', 'Mona Hatoum', 'arte-conceptual', 'londres', 1952],
  ['shahzia-sikander', 'Shahzia Sikander', 'Shahzia Sikander', 'arte-indio', 'delhi', 1969],
  ['subodh-gupta', 'Subodh Gupta', 'Subodh Gupta', 'arte-indio', 'delhi', 1964],
  ['takashi-murakami', 'Takashi Murakami', 'Takashi Murakami', 'arte-conceptual', 'tokio', 1962],
  ['hiroshi-sugimoto', 'Hiroshi Sugimoto', 'Hiroshi Sugimoto', 'fotografia-moderna', 'tokio', 1948],
  ['ryue-nishizawa', 'Ryue Nishizawa', 'Ryue Nishizawa', 'arquitectura-moderna', 'tokio', 1966],
  ['wang-shu', 'Wang Shu', 'Wang Shu', 'arquitectura-moderna', 'pekin', 1963],
  ['shigeru-ban', 'Shigeru Ban', 'Shigeru Ban', 'arquitectura-moderna', 'tokio', 1957],
];

const works: Array<[string, string, string, string | null, string | null, number]> = [
  ['puerta-de-ishtar', 'Puerta de Ishtar', 'Ishtar Gate', 'arte-mesopotamico', null, -575],
  [
    'codigo-de-hammurabi',
    'Código de Hammurabi',
    'Code of Hammurabi',
    'arte-mesopotamico',
    null,
    -1750,
  ],
  ['discobolo', 'Discóbolo', 'Discobolus', 'arte-griego', null, -450],
  ['teatro-de-epidauro', 'Teatro de Epidauro', 'Theatre of Epidaurus', 'arte-griego', null, -340],
  [
    'augusto-de-prima-porta',
    'Augusto de Prima Porta',
    'Augustus of Prima Porta',
    'arte-romano',
    null,
    20,
  ],
  ['columna-de-trajano', 'Columna de Trajano', 'Trajan’s Column', 'arte-romano', null, 113],
  [
    'icono-de-cristo-pantocrator',
    'Cristo Pantocrátor',
    'Christ Pantocrator',
    'arte-bizantino',
    null,
    1100,
  ],
  [
    'mezquita-de-samarra',
    'Gran Mezquita de Samarra',
    'Great Mosque of Samarra',
    'arte-islamico',
    null,
    851,
  ],
  ['campanile-de-giotto', 'Campanile de Giotto', 'Giotto’s Campanile', 'gotico', 'giotto', 1334],
  [
    'la-expulsion-del-paraiso',
    'La expulsión del paraíso',
    'Expulsion from Paradise',
    'renacimiento-italiano',
    'masaccio',
    1427,
  ],
  ['san-jorge-donato', 'San Jorge', 'Saint George', 'renacimiento-italiano', 'donatello', 1417],
  [
    'flagelacion-de-cristo',
    'La flagelación de Cristo',
    'Flagellation of Christ',
    'renacimiento-italiano',
    'piero-della-francesca',
    1455,
  ],
  [
    'camera-degli-sposi',
    'Cámara de los esposos',
    'Camera degli Sposi',
    'renacimiento-italiano',
    'andrea-mantegna',
    1474,
  ],
  ['la-tempestad', 'La tempestad', 'The Tempest', 'renacimiento-italiano', 'giorgione', 1508],
  [
    'la-virgen-del-cuello-largo',
    'La Virgen del cuello largo',
    'Madonna with the Long Neck',
    'manierismo',
    'pontormo',
    1535,
  ],
  [
    'rapto-de-las-sabinas',
    'Rapto de las sabinas',
    'Rape of the Sabine Women',
    'manierismo',
    'giambologna',
    1583,
  ],
  [
    'asuncion-de-la-virgen-carracci',
    'Asunción de la Virgen',
    'Assumption of the Virgin',
    'barroco',
    'annibale-carracci',
    1600,
  ],
  [
    'hipomenes-y-atlanta',
    'Hipómenes y Atalanta',
    'Hippomenes and Atalanta',
    'barroco',
    'guido-reni',
    1618,
  ],
  [
    'caballero-sonriente',
    'El caballero sonriente',
    'The Laughing Cavalier',
    'barroco',
    'frans-hals',
    1624,
  ],
  [
    'la-magdalena-penitente',
    'La Magdalena penitente',
    'Penitent Magdalene',
    'barroco',
    'georges-de-la-tour',
    1640,
  ],
  ['fiesta-de-amor', 'Fiesta de amor', 'The Pleasures of Love', 'rococo', 'antonie-watteau', 1717],
  [
    'el-banquete-de-cleopatra',
    'El banquete de Cleopatra',
    'The Banquet of Cleopatra',
    'rococo',
    'giambologna',
    1747,
  ],
  ['el-columpio', 'El columpio', 'The Swing', 'rococo', 'jean-honore-fragonard', 1768],
  [
    'psique-reanimada-por-el-beso',
    'Psique reanimada por el beso',
    'Psyche Revived by Cupid’s Kiss',
    'neoclasicismo',
    'antonio-canova',
    1787,
  ],
  [
    'el-caminante-sobre-el-mar-de-nubes',
    'El caminante sobre el mar de nubes',
    'Wanderer above the Sea of Fog',
    'romanticismo',
    'caspar-david-friedrich',
    1818,
  ],
  [
    'la-balsa-de-la-medusa',
    'La balsa de la Medusa',
    'The Raft of the Medusa',
    'romanticismo',
    'theodore-gericault',
    1819,
  ],
  [
    'el-tranvia-de-tercera-clase',
    'El vagón de tercera clase',
    'The Third-Class Carriage',
    'realismo',
    'honore-daumier',
    1864,
  ],
  ['las-espigadoras', 'Las espigadoras', 'The Gleaners', 'realismo', 'jean-francois-millet', 1857],
  [
    'la-porcion-de-la-guerra',
    'La apoteosis de la guerra',
    'The Apotheosis of War',
    'realismo',
    'vassily-vereshchagin',
    1871,
  ],
  [
    'el-ojo-como-globo-extrano',
    'El ojo como globo extraño',
    'The Eye Like a Strange Balloon',
    'simbolismo',
    'odilon-redon',
    1882,
  ],
  [
    'el-juramento-de-los-horacios-estudio',
    'Estudio para el juramento de los Horacios',
    'Study for Oath of the Horatii',
    'neoclasicismo',
    'jacques-louis-david',
    1784,
  ],
  [
    'boulevard-montmartre',
    'Boulevard Montmartre',
    'Boulevard Montmartre',
    'impresionismo',
    'camille-pissarro',
    1897,
  ],
  [
    'la-inundacion-en-port-marly',
    'La inundación en Port-Marly',
    'Flood at Port-Marly',
    'impresionismo',
    'alfred-sisley',
    1876,
  ],
  [
    'una-tarde-de-domingo',
    'Una tarde de domingo',
    'A Sunday on La Grande Jatte',
    'postimpresionismo',
    'georges-seurat',
    1886,
  ],
  [
    'moulin-rouge-la-goulue',
    'Moulin Rouge: La Goulue',
    'Moulin Rouge: La Goulue',
    'postimpresionismo',
    'toulouse-lautrec',
    1891,
  ],
  [
    'bretonas-en-el-prado',
    'Bretonas en el prado',
    'Breton Women in the Meadow',
    'postimpresionismo',
    'emile-bernard',
    1888,
  ],
  ['equivalentes', 'Equivalentes', 'Equivalent', 'fotografia-moderna', 'alfred-stieglitz', 1923],
  ['rayografia', 'Rayografía', 'Rayograph', 'dadaismo', 'man-ray', 1922],
  [
    'dama-en-la-calle',
    'Dama en la calle',
    'Woman on the Street',
    'dadaismo',
    'francis-picabia',
    1920,
  ],
  ['lunar-caustic', 'Lunar Caustic', 'Lunar Caustic', 'dadaismo', 'tristan-tzara', 1920],
  ['danza-vertical', 'Danza vertical', 'Vertical Dance', 'dadaismo', 'sophie-taeuber-arp', 1926],
  [
    'torre-eiffel-robert-delaunay',
    'Torre Eiffel',
    'Eiffel Tower',
    'orfismo',
    'robert-delaunay',
    1911,
  ],
  ['cuadro-negro-popova', 'Cuadro negro', 'Black Square', 'constructivismo', 'liubov-popova', 1918],
  ['el-ciclista', 'El ciclista', 'The Cyclist', 'futurismo', 'natalia-goncharova', 1913],
  [
    'la-ciudad-al-final-del-mundo',
    'La ciudad al final del mundo',
    'City at the End of the World',
    'bauhaus-movement',
    'lyonel-feininger',
    1928,
  ],
  [
    'homenaje-al-cuadrado',
    'Homenaje al cuadrado',
    'Homage to the Square',
    'bauhaus-movement',
    'josef-albers',
    1950,
  ],
  [
    'modulador-espacio-luz',
    'Modulador espacio-luz',
    'Light-Space Modulator',
    'bauhaus-movement',
    'laszlo-moholy-nagy',
    1930,
  ],
  [
    'ballet-tríadico',
    'Ballet triádico',
    'Triadic Ballet',
    'bauhaus-movement',
    'oskar-schlemmer',
    1922,
  ],
  [
    'retrato-de-manuela',
    'Retrato de Manuela',
    'Portrait of Manuela',
    'realismo',
    'alice-neel',
    1965,
  ],
  ['cartel-de-la-guerra', 'Cartel de la guerra', 'War Poster', 'realismo', 'ben-shahn', 1943],
  [
    'early-mail-service-and-construction-of-railroads-mural-study',
    'Early Mail Service and Construction of Railroads (mural study, Commerce, Georgia Post Office)',
    'Early Mail Service and Construction of Railroads (mural study, Commerce, Georgia Post Office)',
    null,
    'philip-guston',
    1938,
  ],
  ['composicion', 'Composición', 'Composition', 'expresionismo-abstracto', 'lee-krasner', 1955],
  [
    'montanas-y-mar',
    'Montañas y mar',
    'Mountains and Sea',
    'expresionismo-abstracto',
    'helen-frankenthaler',
    1952,
  ],
  ['sin-titulo-twombly', 'Sin título', 'Untitled', 'expresionismo-abstracto', 'cy-twombly', 1968],
  ['monograma', 'Monograma', 'Monogram', 'pop-art', 'robert-rauschenberg', 1955],
  ['bandera', 'Bandera', 'Flag', 'pop-art', 'jasper-johns', 1955],
  ['soft-sculpture', 'Escultura blanda', 'Soft Sculpture', 'pop-art', 'claes-oldenburg', 1962],
  ['catarata', 'Catarata', 'Cataract', 'minimalismo', 'bridget-riley', 1967],
  ['arco-inclinado', 'Arco inclinado', 'Tilted Arc', 'minimalismo', 'richard-serra', 1981],
  ['sin-titulo-morris', 'Sin título', 'Untitled', 'minimalismo', 'robert-morris', 1965],
  [
    'monumento-para-v',
    'Monumento para V. Tatlin',
    'Monument for V. Tatlin',
    'minimalismo',
    'dan-flavin',
    1964,
  ],
  [
    'the-dinner-party',
    'The Dinner Party',
    'The Dinner Party',
    'arte-conceptual',
    'judy-chicago',
    1979,
  ],
  [
    'manhattan-real-estate-holdings',
    'Manhattan Real Estate Holdings',
    'Manhattan Real Estate Holdings',
    'arte-conceptual',
    'hans-haacke',
    1971,
  ],
  [
    'semiotica-de-la-cocina',
    'Semiotics of the Kitchen',
    'Semiotics of the Kitchen',
    'arte-conceptual',
    'martha-rosler',
    1975,
  ],
  ['nadie-olvida-nada-1', 'Nadie olvida nada', 'Nadie olvida nada', null, 'guillermo-kuitca', 1982],
  ['fisicromia', 'Fisicromía', 'Physichromie', 'arte-conceptual', 'carlos-cruz-diez', 1965],
  ['los-guerreros', 'Los guerreros', 'The Warriors', 'arte-conceptual', 'lygia-clark', 1960],
  ['divisor', 'Divisor', 'Divisor', 'arte-conceptual', 'lygia-pape', 1968],
  [
    'insertion-into-circuit',
    'Inserción en circuitos ideológicos',
    'Insertions into Ideological Circuits',
    'arte-conceptual',
    'cildo-meireles',
    1970,
  ],
  [
    'apuntes-para-la-historia-del-arte',
    'Apuntes para la historia del arte',
    'Notes for Art History',
    'arte-conceptual',
    'beatriz-gonzalez',
    1980,
  ],
  ['the-cleaner', 'The Cleaner', 'The Cleaner', 'arte-conceptual', 'oscar-murillo', 2015],
  ['magdalena', 'Magdalena', 'Magdalena', 'arte-conceptual', 'marlene-dumas', 1995],
  [
    'freischwimmer',
    'Freischwimmer',
    'Freischwimmer',
    'fotografia-moderna',
    'wolfgang-tillmans',
    2004,
  ],
  [
    'suite-veneciana',
    'Suite Vénitienne',
    'Suite Vénitienne',
    'arte-conceptual',
    'sophie-calle',
    1980,
  ],
  ['blue-print', 'Blue Print', 'Blue Print', 'arte-conceptual', 'walid-beshtي', 2005],
  ['seul-hogar', 'Seoul Home', 'Seoul Home', 'arte-conceptual', 'do-ho-suh', 1999],
  [
    'mirror-ball',
    'Mirror Ball',
    'Mirror Ball',
    'arte-conceptual',
    'monir-shahroudy-farmanfarmaian',
    1970,
  ],
  ['double-plot', 'Double Plot', 'Double Plot', 'arte-conceptual', 'otobong-nkanga', 2018],
  [
    'faces-and-phases',
    'Faces and Phases',
    'Faces and Phases',
    'fotografia-moderna',
    'zanele-muholi',
    2010,
  ],
  [
    'the-last-sound',
    'The Last Sound',
    'The Last Sound',
    'arte-africano',
    'ibrahim-el-salahi',
    1964,
  ],
  [
    'la-boca-del-tiempo',
    'La bouche du temps',
    'The Mouth of Time',
    'arte-africano',
    'romuald-hazoume',
    2004,
  ],
  [
    'otobo-hippo-masquerade',
    'Otobo (Hippo) masquerade',
    'Otobo (Hippo) masquerade',
    null,
    'sokari-douglas-camp',
    1995,
  ],
  ['modern-magic', 'Modern Magic', 'Modern Magic', 'arte-conceptual', 'henrike-naumann', 2017],
  ['hot-spot', 'Hot Spot', 'Hot Spot', 'arte-conceptual', 'mona-hatoum', 2006],
  ['fleshly-sight', 'Fleshly Sight', 'Fleshly Sight', 'arte-indio', 'shahzia-sikander', 2004],
  ['very-hungry-god', 'Very Hungry God', 'Very Hungry God', 'arte-indio', 'subodh-gupta', 2006],
  ['tan-tan-bo', 'Tan Tan Bo', 'Tan Tan Bo', 'arte-conceptual', 'takashi-murakami', 2001],
  ['seascapes', 'Seascapes', 'Seascapes', 'fotografia-moderna', 'hiroshi-sugimoto', 1980],
  ['the-trees', 'The Trees', 'The Trees', 'arquitectura-moderna', 'ryue-nishizawa', 2009],
  ['paper-church', 'Paper Church', 'Paper Church', 'arquitectura-moderna', 'shigeru-ban', 1995],
];

const concepts = [
  ['icono', 'Icono', 'Icon'],
  ['alegoria', 'Alegoría', 'Allegory'],
  ['canon', 'Canon', 'Canon'],
  ['perspectiva-aerea', 'Perspectiva aérea', 'Aerial perspective'],
  ['claroscuro', 'Claroscuro', 'Chiaroscuro'],
  ['sfumato', 'Sfumato', 'Sfumato'],
  ['tenebrismo', 'Tenebrism', 'Tenebrism'],
  ['ornamento', 'Ornamento', 'Ornament'],
  ['simetria', 'Simetría', 'Symmetry'],
  ['proporcion', 'Proporción', 'Proportion'],
  ['ritmo', 'Ritmo', 'Rhythm'],
  ['escala', 'Escala', 'Scale'],
  ['espacio', 'Espacio', 'Space'],
  ['forma', 'Forma', 'Form'],
  ['color', 'Color', 'Color'],
  ['linea', 'Línea', 'Line'],
  ['textura', 'Textura', 'Texture'],
  ['luz', 'Luz', 'Light'],
  ['sombra', 'Sombra', 'Shadow'],
  ['huella', 'Huella', 'Trace'],
  ['fragmento', 'Fragmento', 'Fragment'],
  ['ruina', 'Ruina', 'Ruin'],
  ['monstruo', 'Monstruo', 'Monster'],
  ['animal', 'Animal', 'Animal'],
  ['planta', 'Planta', 'Plant'],
  ['agua', 'Agua', 'Water'],
  ['fuego', 'Fuego', 'Fire'],
  ['tierra', 'Tierra', 'Earth'],
  ['aire', 'Aire', 'Air'],
  ['sagrado', 'Sagrado', 'Sacred'],
  ['profano', 'Profano', 'Profane'],
  ['secularizacion', 'Secularización', 'Secularization'],
  ['nacion', 'Nación', 'Nation'],
  ['frontera', 'Frontera', 'Border'],
  ['territorio', 'Territorio', 'Territory'],
  ['pueblo', 'Pueblo', 'People'],
  ['trabajador', 'Trabajador', 'Worker'],
  ['industria', 'Industria', 'Industry'],
  ['consumo', 'Consumo', 'Consumption'],
  ['medios-de-masas', 'Medios de masas', 'Mass media'],
  ['publicidad', 'Publicidad', 'Advertising'],
  ['exposicion', 'Exposición', 'Exhibition'],
  ['museo', 'Museo', 'Museum'],
  ['academia', 'Academia', 'Academy'],
  ['taller', 'Taller', 'Workshop'],
  ['escuela', 'Escuela', 'School'],
  ['vanguardia', 'Vanguardia', 'Avant-garde'],
  ['posmodernidad', 'Posmodernidad', 'Postmodernity'],
  ['globalizacion', 'Globalización', 'Globalization'],
  ['digital', 'Digital', 'Digital'],
  ['red', 'Red', 'Network'],
  ['interactividad', 'Interactividad', 'Interactivity'],
  ['participacion', 'Participación', 'Participation'],
  ['archivo-vivo', 'Archivo vivo', 'Living archive'],
  ['testimonio', 'Testimonio', 'Testimony'],
  ['trauma', 'Trauma', 'Trauma'],
  ['duelo', 'Duelo', 'Mourning'],
  ['esperanza', 'Esperanza', 'Hope'],
  ['utopia', 'Utopía', 'Utopia'],
  ['distopia', 'Distopía', 'Dystopia'],
  ['sostenibilidad', 'Sostenibilidad', 'Sustainability'],
  ['clima', 'Clima', 'Climate'],
  ['agua-politica', 'Agua y política', 'Water politics'],
  ['frontera-colonial', 'Frontera colonial', 'Colonial border'],
  ['traduccion', 'Traducción', 'Translation'],
  ['lenguaje', 'Lenguaje', 'Language'],
  ['poesia', 'Poesía', 'Poetry'],
  ['musica', 'Música', 'Music'],
  ['danza', 'Danza', 'Dance'],
  ['teatro', 'Teatro', 'Theatre'],
  ['arquitectura-domestica', 'Arquitectura doméstica', 'Domestic architecture'],
  ['espacio-publico', 'Espacio público', 'Public space'],
  ['paisaje-urbano', 'Paisaje urbano', 'Urban landscape'],
  ['paisaje-rural', 'Paisaje rural', 'Rural landscape'],
  ['cultura-popular', 'Cultura popular', 'Popular culture'],
  ['folclore', 'Folclore', 'Folklore'],
  ['artesania', 'Artesanía', 'Craft'],
  ['ceramica', 'Cerámica', 'Ceramics'],
  ['textil', 'Textil', 'Textile'],
  ['joyeria', 'Joyería', 'Jewelry'],
  ['moda', 'Moda', 'Fashion'],
  ['diseño-grafico', 'Diseño gráfico', 'Graphic design'],
  ['tipografia', 'Tipografía', 'Typography'],
  ['video', 'Vídeo', 'Video'],
  ['sonido', 'Sonido', 'Sound'],
  ['realidad-virtual', 'Realidad virtual', 'Virtual reality'],
  ['inteligencia-artificial', 'Inteligencia artificial', 'Artificial intelligence'],
];

const concepts2 = [
  ['sostenibilidad-urbana', 'Sostenibilidad urbana', 'Urban sustainability'],
  ['patrimonio', 'Patrimonio', 'Heritage'],
  ['restitucion', 'Restitución', 'Restitution'],
  ['repatriacion', 'Repatriación', 'Repatriation'],
  ['censura', 'Censura', 'Censorship'],
  ['activismo', 'Activismo', 'Activism'],
  ['feminismo', 'Feminismo', 'Feminism'],
  ['queer', 'Queer', 'Queer'],
  ['discapacidad', 'Discapacidad', 'Disability'],
  ['accesibilidad', 'Accesibilidad', 'Accessibility'],
  ['cuerpo-politico', 'Cuerpo político', 'Political body'],
  ['tecnicas-de-reproduccion', 'Técnicas de reproducción', 'Reproductive technologies'],
  ['propiedad', 'Propiedad', 'Property'],
  ['mercado-del-arte', 'Mercado del arte', 'Art market'],
  ['conservacion', 'Conservación', 'Conservation'],
  ['restauracion', 'Restauración', 'Restoration'],
  ['patrimonio-inmaterial', 'Patrimonio inmaterial', 'Intangible heritage'],
  ['museologia', 'Museología', 'Museology'],
  ['turismo-cultural', 'Turismo cultural', 'Cultural tourism'],
  ['derechos-culturales', 'Derechos culturales', 'Cultural rights'],
];

const places = [
  ['mantua', 'Mantua', 'Mantua'],
  ['bogota', 'Bogotá', 'Bogotá'],
  ['los-angeles', 'Los Ángeles', 'Los Angeles'],
  ['seul', 'Seúl', 'Seoul'],
  ['teheran', 'Teherán', 'Tehran'],
  ['bucarest', 'Bucarest', 'Bucharest'],
  ['jartum', 'Jartum', 'Khartoum'],
];

const slugify = (value: string) =>
  value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
const rawExpansion2Entities: FoundationalEntity[] = [
  ...people.map(([slug, title, en, movement, place, start, end]) =>
    e(slug, 'ARTIST', title, en, 'people', start, end),
  ),
  ...works.map(([slug, title, en, movement, creator, year]) =>
    e(slug, 'ARTWORK', title, en, 'works', year, year),
  ),
  ...concepts.map(([slug, title, en]) => e(slug, 'CONCEPT', title, en, 'cross-period concepts')),
  ...concepts2.map(([slug, title, en]) => e(slug, 'CONCEPT', title, en, 'cross-period concepts')),
  ...places.map(([slug, title, en]) => e(slug, 'PLACE', title, en, 'places')),
];

const rawExpansion2Relations: FoundationalRelation[] = [
  ...people.flatMap(([person, , , movement, place]) => [
    rel(person, movement, 'BELONGS_TO_MOVEMENT'),
    rel(person, place, 'LOCATED_IN'),
  ]),
  ...works.flatMap(([work, , , movement, creator]) => [
    ...(creator
      ? [rel(work, creator === 'walid-beshtي' ? 'walid-beshty' : creator, 'CREATED_BY')]
      : []),
    ...(movement ? [rel(work, movement, 'BELONGS_TO_MOVEMENT')] : []),
  ]),
];

export const expansion2Entities = rawExpansion2Entities.map((entity) => ({
  ...entity,
  slug: slugify(entity.slug),
}));
export const expansion2Relations = rawExpansion2Relations.map((relation) => ({
  ...relation,
  from: slugify(relation.from),
  to: slugify(relation.to),
}));
