import type { FoundationalEntity, FoundationalRelation } from './types';

const row = (
  slug: string,
  title: string,
  en: string,
  creator: string,
  movement: string,
  year: number,
): [FoundationalEntity, FoundationalRelation[]] => [
  { slug, type: 'ARTWORK', title, en, block: 'works', tier: 'B', startYear: year, endYear: year },
  [
    { from: slug, to: creator, type: 'CREATED_BY' },
    { from: slug, to: movement, type: 'BELONGS_TO_MOVEMENT' },
    { from: slug, to: 'representacion', type: 'ABOUT_CONCEPT' },
  ],
];

const rows: Array<[string, string, string, string, string, number]> = [
  [
    'vision-despues-del-sermon',
    'Visión después del sermón',
    'The Vision after the Sermon',
    'paul-gauguin',
    'postimpresionismo',
    1888,
  ],
  ['la-danza-matisse', 'La danza', 'The Dance', 'henri-matisse', 'fauvismo', 1910],
  [
    'violin-y-candela',
    'Violín y candela',
    'Violin and Candlestick',
    'georges-braque',
    'cubismo',
    1910,
  ],
  [
    'carnaval-del-arlequin',
    'El carnaval del arlequín',
    'The Harlequin’s Carnival',
    'joan-miro',
    'surrealismo',
    1924,
  ],
  ['villa-savoye', 'Villa Savoye', 'Villa Savoye', 'le-corbusier', 'arquitectura-moderna', 1929],
  [
    'los-diez-mayores',
    'Los diez mayores',
    'The Ten Largest',
    'hilma-af-klint',
    'abstraccion',
    1907,
  ],
  ['jimson-weed', 'Jimson Weed', 'Jimson Weed', 'georgia-okeeffe', 'abstraccion', 1936],
  [
    'retrato-de-giovanni-arnolfini',
    'Retrato de Giovanni Arnolfini',
    'Arnolfini Portrait',
    'jan-van-eyck',
    'renacimiento-nordico',
    1434,
  ],
  ['melancolia-i', 'Melancolía I', 'Melencolia I', 'albrecht-durer', 'renacimiento-nordico', 1514],
  [
    'cazadores-en-la-nieve',
    'Cazadores en la nieve',
    'The Hunters in the Snow',
    'pieter-bruegel',
    'renacimiento-nordico',
    1565,
  ],
  [
    'elevacion-de-la-cruz',
    'La elevación de la cruz',
    'The Elevation of the Cross',
    'peter-paul-rubens',
    'barroco',
    1610,
  ],
  [
    'judith-y-su-doncella',
    'Judith y su doncella',
    'Judith and Her Maidservant',
    'artemisia-gentileschi',
    'barroco',
    1614,
  ],
  ['el-pie-zambo', 'El patizambo', 'The Clubfoot', 'jose-de-ribera', 'barroco', 1642],
  [
    'inmaculada-de-soult',
    'Inmaculada de Soult',
    'Soult Immaculate',
    'bartolome-esteban-murillo',
    'barroco',
    1678,
  ],
  [
    'el-anciano-de-los-dias',
    'El anciano de los días',
    'The Ancient of Days',
    'william-blake',
    'romanticismo',
    1794,
  ],
  [
    'el-carro-de-heno',
    'La carreta de heno',
    'The Hay Wain',
    'john-constable',
    'romanticismo',
    1821,
  ],
  [
    'la-feria-de-caballos',
    'La feria de caballos',
    'The Horse Fair',
    'rosa-bonheur',
    'realismo',
    1853,
  ],
  ['la-cuna', 'La cuna', 'The Cradle', 'berthe-morisot', 'impresionismo', 1872],
  [
    'el-bano-del-nino',
    'El baño del niño',
    'The Child’s Bath',
    'mary-cassatt',
    'impresionismo',
    1893,
  ],
  [
    'autorretrato-con-linterna',
    'Autorretrato con farol chino',
    'Self-Portrait with Chinese Lantern',
    'egon-schiele',
    'expresionismo',
    1912,
  ],
  [
    'calle-de-berlin',
    'Calle de Berlín',
    'Berlin Street',
    'ernst-ludwig-kirchner',
    'expresionismo',
    1913,
  ],
  [
    'maquina-de-trinar',
    'Máquina de trinar',
    'Twittering Machine',
    'paul-klee',
    'bauhaus-movement',
    1922,
  ],
  [
    'prismas-electricos',
    'Prismas eléctricos',
    'Electric Prisms',
    'sonia-delaunay',
    'orfismo',
    1914,
  ],
  [
    'vence a los blancos con la cuña roja',
    'Vence a los blancos con la cuña roja',
    'Beat the Whites with the Red Wedge',
    'el-lissitzky',
    'constructivismo',
    1919,
  ],
  [
    'corte con el cuchillo de cocina',
    'Corte con el cuchillo de cocina',
    'Cut with the Kitchen Knife',
    'hannah-hoch',
    'dadaismo',
    1919,
  ],
  [
    'dos niños amenazados por un ruiseñor',
    'Dos niños amenazados por un ruiseñor',
    'Two Children Are Threatened by a Nightingale',
    'max-ernst',
    'surrealismo',
    1924,
  ],
  [
    'pajaro en el espacio',
    'Pájaro en el espacio',
    'Bird in Space',
    'constantin-brancusi',
    'abstraccion',
    1928,
  ],
  ['contingente', 'Contingente', 'Contingent', 'eva-hesse', 'minimalismo', 1969],
  ['sin titulo judd', 'Sin título', 'Untitled', 'donald-judd', 'minimalismo', 1969],
  [
    'dibujo mural 118',
    'Dibujo mural 118',
    'Wall Drawing 118',
    'sol-lewitt',
    'arte-conceptual',
    1971,
  ],
  ['amistad', 'Amistad', 'Friendship', 'agnes-martin', 'minimalismo', 1963],
  [
    'tierra desarrollando mas raices',
    'Tierra desarrollando más raíces',
    'Earth Developing More Roots',
    'el-anatsui',
    'arte-africano',
    2018,
  ],
  [
    'felix en el exilio',
    'Felix en el exilio',
    'Felix in Exile',
    'william-kentridge',
    'arte-conceptual',
    1994,
  ],
  [
    'dorchester projects',
    'Dorchester Projects',
    'Dorchester Projects',
    'theaster-gates',
    'arte-conceptual',
    2009,
  ],
  [
    'antropofagia',
    'Antropofagia',
    'Anthropophagy',
    'oswald-de-andrade',
    'modernismo-brasileno',
    1928,
  ],
  [
    'creacion de las aves',
    'Creación de las aves',
    'Creation of the Birds',
    'remedios-varo',
    'surrealismo',
    1957,
  ],
  [
    'eco de un grito',
    'Eco de un grito',
    'Echo of a Scream',
    'david-alfaro-siqueiros',
    'muralismo-mexicano',
    1937,
  ],
  [
    'la corriente del golfo',
    'La corriente del Golfo',
    'The Gulf Stream',
    'winslow-homer',
    'realismo',
    1899,
  ],
  [
    'la anunciacion fra angelico',
    'La Anunciación',
    'The Annunciation',
    'fra-angelico',
    'renacimiento-italiano',
    1438,
  ],
  [
    'madame de pompadour',
    'Madame de Pompadour',
    'Madame de Pompadour',
    'francois-boucher',
    'rococo',
    1756,
  ],
  [
    'jupiter y semele',
    'Júpiter y Sémele',
    'Jupiter and Semele',
    'gustave-moreau',
    'simbolismo',
    1894,
  ],
  ['el pequeño camello', 'El pequeño camello', 'The Little Camel', 'elena-guro', 'futurismo', 1910],
  [
    'autorretrato manuela ballester',
    'Autorretrato',
    'Self-Portrait',
    'manuela-ballester',
    'realismo',
    1940,
  ],
  [
    'museo de ningbo',
    'Museo de Ningbo',
    'Ningbo Historic Museum',
    'wang-shu',
    'arquitectura-moderna',
    2008,
  ],
];

export const expansion3People: FoundationalEntity[] = [
  {
    slug: 'otobong-nkanga',
    type: 'ARTIST',
    title: 'Otobong Nkanga',
    en: 'Otobong Nkanga',
    block: 'people',
    tier: 'B',
    startYear: 1974,
  },
  {
    slug: 'winslow-homer',
    type: 'ARTIST',
    title: 'Winslow Homer',
    en: 'Winslow Homer',
    block: 'people',
    tier: 'B',
    startYear: 1836,
    endYear: 1910,
    aliases: ['Winslow Homer'],
  },
  {
    slug: 'doris-salcedo',
    type: 'ARTIST',
    title: 'Doris Salcedo',
    en: 'Doris Salcedo',
    block: 'people',
    tier: 'B',
    startYear: 1958,
  },
  {
    slug: 'william-morris',
    type: 'ARTIST',
    title: 'William Morris',
    en: 'William Morris',
    block: 'people',
    tier: 'B',
    startYear: 1834,
    endYear: 1896,
  },
  {
    slug: 'piet-mondrian',
    type: 'ARTIST',
    title: 'Piet Mondrian',
    en: 'Piet Mondrian',
    block: 'people',
    tier: 'B',
    startYear: 1872,
    endYear: 1944,
  },
  {
    slug: 'jean-fautrier',
    type: 'ARTIST',
    title: 'Jean Fautrier',
    en: 'Jean Fautrier',
    block: 'people',
    tier: 'B',
    startYear: 1898,
    endYear: 1964,
  },
  {
    slug: 'robert-smithson',
    type: 'ARTIST',
    title: 'Robert Smithson',
    en: 'Robert Smithson',
    block: 'people',
    tier: 'B',
    startYear: 1938,
    endYear: 1973,
  },
];
export const expansion3PeopleRelations: FoundationalRelation[] = [
  { from: 'otobong-nkanga', to: 'arte-africano', type: 'BELONGS_TO_MOVEMENT' },
  { from: 'otobong-nkanga', to: 'lagos', type: 'LOCATED_IN' },
  { from: 'winslow-homer', to: 'realismo', type: 'BELONGS_TO_MOVEMENT' },
  { from: 'winslow-homer', to: 'nueva-york', type: 'LOCATED_IN' },
  { from: 'doris-salcedo', to: 'arte-conceptual', type: 'BELONGS_TO_MOVEMENT' },
  { from: 'doris-salcedo', to: 'bogota', type: 'LOCATED_IN' },
  { from: 'william-morris', to: 'arts-and-crafts', type: 'BELONGS_TO_MOVEMENT' },
  { from: 'william-morris', to: 'londres', type: 'LOCATED_IN' },
  { from: 'piet-mondrian', to: 'de-stijl', type: 'BELONGS_TO_MOVEMENT' },
  { from: 'piet-mondrian', to: 'paris', type: 'LOCATED_IN' },
  { from: 'jean-fautrier', to: 'informalismo', type: 'BELONGS_TO_MOVEMENT' },
  { from: 'jean-fautrier', to: 'paris', type: 'LOCATED_IN' },
  { from: 'robert-smithson', to: 'land-art', type: 'BELONGS_TO_MOVEMENT' },
  { from: 'robert-smithson', to: 'nueva-york', type: 'LOCATED_IN' },
  { from: 'ai-weiwei', to: 'arte-chino', type: 'BELONGS_TO_MOVEMENT' },
  { from: 'marina-abramovic', to: 'arte-performance', type: 'BELONGS_TO_MOVEMENT' },
];

const additionalRows: Array<[string, string, string, string, string, number]> = [
  [
    'self-portrait-angelica-kauffmann',
    'Autorretrato',
    'Self-Portrait',
    'angelica-kauffmann',
    'neoclasicismo',
    1770,
  ],
  ['red-house-morris', 'Red House', 'Red House', 'william-morris', 'arts-and-crafts', 1860],
  [
    'composicion-rojo-azul-amarillo',
    'Composición con rojo, azul y amarillo',
    'Composition with Red, Blue and Yellow',
    'piet-mondrian',
    'de-stijl',
    1930,
  ],
  ['otages-fautrier', 'Rehenes', 'Hostages', 'jean-fautrier', 'informalismo', 1945],
  ['spiral-jetty', 'Embarcadero espiral', 'Spiral Jetty', 'robert-smithson', 'land-art', 1970],
  [
    'no-linear-narrative',
    'Narrativa no lineal',
    'A Non-Linear Narrative',
    'amara-kanwar',
    'arte-indio',
    2004,
  ],
];
const slugify = (value: string) =>
  value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
const normalizedRows = [...rows, ...additionalRows].map(
  ([slug, title, en, creator, movement, year]) =>
    [slugify(slug), title, en, creator, movement, year] as const,
);

export const expansion3Entities = normalizedRows.map(([slug, title, en, , , year]) => ({
  slug,
  type: 'ARTWORK' as const,
  title,
  en,
  block: 'works',
  tier: 'B' as const,
  startYear: year,
  endYear: year,
}));
export const expansion3Relations = normalizedRows.flatMap(
  ([slug, , , creator, movement]) =>
    [
      { from: slug, to: creator, type: 'CREATED_BY' },
      { from: slug, to: movement, type: 'BELONGS_TO_MOVEMENT' },
      { from: slug, to: 'representacion', type: 'ABOUT_CONCEPT' },
    ] satisfies FoundationalRelation[],
);
