import type { FoundationalEntity, FoundationalRelation } from './types';

const row = (
  slug: string,
  type: FoundationalEntity['type'],
  title: string,
  en: string,
  block: string,
  startYear?: number,
  endYear?: number,
  aliases?: string[],
): FoundationalEntity => ({ slug, type, title, en, block, tier: 'B', startYear, endYear, aliases });
const relation = (from: string, to: string, type: string): FoundationalRelation => ({
  from,
  to,
  type,
});

export const extraEntities: FoundationalEntity[] = [
  ...[
    ['orfismo', 'Orfismo', 'Orphism'],
    ['fotografia-moderna', 'Fotografía moderna', 'Modern photography'],
    ['arte-performance', 'Arte de performance', 'Performance art'],
  ].map(([slug, title, en]) => row(slug, 'MOVEMENT', title, en, 'movements')),
  ...[
    ['aristoteles', 'Aristóteles', 'Aristotle', -384, -322],
    ['plinio-el-viejo', 'Plinio el Viejo', 'Pliny the Elder', 23, 79],
    ['agustin-de-hipona', 'Agustín de Hipona', 'Augustine of Hippo', 354, 430],
    ['giotto', 'Giotto di Bondone', 'Giotto', 1267, 1337],
    ['jan-van-eyck', 'Jan van Eyck', 'Jan van Eyck', 1390, 1441],
    ['albrecht-durer', 'Albrecht Dürer', 'Albrecht Dürer', 1471, 1528],
    ['pieter-bruegel', 'Pieter Bruegel el Viejo', 'Pieter Bruegel the Elder', 1525, 1569],
    ['peter-paul-rubens', 'Peter Paul Rubens', 'Peter Paul Rubens', 1577, 1640],
    ['artemisia-gentileschi', 'Artemisia Gentileschi', 'Artemisia Gentileschi', 1593, 1656],
    ['jose-de-ribera', 'José de Ribera', 'Jusepe de Ribera', 1591, 1652],
    [
      'bartolome-esteban-murillo',
      'Bartolomé Esteban Murillo',
      'Bartolomé Esteban Murillo',
      1617,
      1682,
    ],
    ['canaletto', 'Canaletto', 'Canaletto', 1697, 1768],
    ['william-blake', 'William Blake', 'William Blake', 1757, 1827],
    ['jmw-turner', 'J. M. W. Turner', 'J. M. W. Turner', 1775, 1851],
    ['john-constable', 'John Constable', 'John Constable', 1776, 1837],
    ['rosa-bonheur', 'Rosa Bonheur', 'Rosa Bonheur', 1822, 1899],
    ['berthe-morisot', 'Berthe Morisot', 'Berthe Morisot', 1841, 1895],
    ['mary-cassatt', 'Mary Cassatt', 'Mary Cassatt', 1844, 1926],
    ['odilon-redon', 'Odilon Redon', 'Odilon Redon', 1840, 1916],
    ['gustav-klimt', 'Gustav Klimt', 'Gustav Klimt', 1862, 1918],
    ['egon-schiele', 'Egon Schiele', 'Egon Schiele', 1890, 1918],
    ['ernst-ludwig-kirchner', 'Ernst Ludwig Kirchner', 'Ernst Ludwig Kirchner', 1880, 1938],
    ['paul-klee', 'Paul Klee', 'Paul Klee', 1879, 1940],
    ['sonia-delaunay', 'Sonia Delaunay', 'Sonia Delaunay', 1885, 1979],
    ['el-lissitzky', 'El Lissitzky', 'El Lissitzky', 1890, 1941],
    ['hannah-hoch', 'Hannah Höch', 'Hannah Höch', 1889, 1978],
    ['rene-magritte', 'René Magritte', 'René Magritte', 1898, 1967],
    ['max-ernst', 'Max Ernst', 'Max Ernst', 1891, 1976],
    ['meret-oppenheim', 'Meret Oppenheim', 'Meret Oppenheim', 1913, 1985],
    ['alexander-calder', 'Alexander Calder', 'Alexander Calder', 1898, 1976],
    ['constantin-brancusi', 'Constantin Brâncuși', 'Constantin Brâncuși', 1876, 1957],
    ['eva-hesse', 'Eva Hesse', 'Eva Hesse', 1936, 1970],
    ['donald-judd', 'Donald Judd', 'Donald Judd', 1928, 1994],
    ['sol-lewitt', 'Sol LeWitt', 'Sol LeWitt', 1928, 2007],
    ['agnes-martin', 'Agnes Martin', 'Agnes Martin', 1912, 2004],
    ['cindy-sherman', 'Cindy Sherman', 'Cindy Sherman', 1954],
    ['carrie-mae-weems', 'Carrie Mae Weems', 'Carrie Mae Weems', 1953],
    ['shirin-neshat', 'Shirin Neshat', 'Shirin Neshat', 1957],
    ['el-anatsui', 'El Anatsui', 'El Anatsui', 1944],
    ['william-kentridge', 'William Kentridge', 'William Kentridge', 1955],
    ['theaster-gates', 'Theaster Gates', 'Theaster Gates', 1973],
    ['tarsila-do-amaral', 'Tarsila do Amaral', 'Tarsila do Amaral', 1886, 1973],
    ['oswald-de-andrade', 'Oswald de Andrade', 'Oswald de Andrade', 1890, 1954],
    ['wifredo-lam', 'Wifredo Lam', 'Wifredo Lam', 1902, 1982],
    ['remedios-varo', 'Remedios Varo', 'Remedios Varo', 1908, 1963],
    ['david-alfaro-siqueiros', 'David Alfaro Siqueiros', 'David Alfaro Siqueiros', 1896, 1974],
    ['joseph-kosuth', 'Joseph Kosuth', 'Joseph Kosuth', 1945],
    ['heli-oiticica', 'Hélio Oiticica', 'Hélio Oiticica', 1937, 1980],
  ].map(([slug, title, en, start, end]) =>
    row(
      slug as string,
      'ARTIST',
      title as string,
      en as string,
      'people',
      start as number | undefined,
      end as number | undefined,
    ),
  ),
  ...[
    ['mezquita-azul', 'Mezquita Azul', 'Blue Mosque', 1609, 1616],
    ['palacio-de-versailles', 'Palacio de Versalles', 'Palace of Versailles', 1661, 1715],
    ['canaletto-gran-canal', 'El Gran Canal', 'The Grand Canal', 1730],
    ['vapor-y-nubes-de-steam-boat', 'Lluvia, vapor y velocidad', 'Rain, Steam and Speed', 1844],
    ['la-clase-de-danza', 'La clase de danza', 'The Dance Class', 1874],
    ['el-barco-de-esclavos', 'El barco de esclavos', 'The Slave Ship', 1840],
    ['el-beso-klimt', 'El beso', 'The Kiss', 1907, 1908],
    [
      'retrato-de-adele-bloch-bauer',
      'Retrato de Adele Bloch-Bauer I',
      'Portrait of Adele Bloch-Bauer I',
      1907,
    ],
    [
      'autorretrato-con-collar-de-espinas',
      'Autorretrato con collar de espinas',
      'Self-Portrait with Thorn Necklace',
      1940,
    ],
    ['el-hijo-del-hombre', 'El hijo del hombre', 'The Son of Man', 1964],
    ['lobster-telephone', 'Teléfono langosta', 'Lobster Telephone', 1938],
    ['objeto-para-ser-destruido', 'Objeto para ser destruido', 'Object to Be Destroyed', 1931],
    ['mobile-calder-rojo', 'Móvil rojo', 'Red Mobile', 1956],
    ['obra-de-arte-en-el-tiempo', 'One and Three Chairs', 'One and Three Chairs', 1965],
    ['cuerpo-como-archivo', 'The Body as Archive', 'The Body as Archive', 1998],
    ['shibboleth', 'Shibboleth', 'Shibboleth', 2007],
    ['tropicalia-obra', 'Tropicália', 'Tropicália', 1967],
    ['abaporu', 'Abaporu', 'Abaporu', 1928],
    ['la-jungla-lam', 'La jungla', 'The Jungle', 1943],
    ['untitled-film-still-21', 'Untitled Film Still #21', 'Untitled Film Still #21', 1978],
    [
      'from-here-i-saw-what-happened',
      'From Here I Saw What Happened',
      'From Here I Saw What Happened',
      1995,
    ],
  ].map(([slug, title, en, start, end]) =>
    row(
      slug as string,
      'ARTWORK',
      title as string,
      en as string,
      'works',
      start as number | undefined,
      end as number | undefined,
    ),
  ),
  ...[
    ['museo-britanico', 'Museo Británico', 'British Museum'],
    ['museo-egipcio-cairo', 'Museo Egipcio de El Cairo', 'Egyptian Museum Cairo'],
    [
      'museo-nacional-antropologia',
      'Museo Nacional de Antropología',
      'National Museum of Anthropology',
    ],
    ['instituto-warburg', 'Instituto Warburg', 'Warburg Institute'],
    ['escuela-de-atenas-institucion', 'Escuela de Atenas', 'School of Athens'],
    ['black-mountain-college', 'Black Mountain College', 'Black Mountain College'],
    ['instituto-de-arte-chicago', 'Instituto de Arte de Chicago', 'Art Institute of Chicago'],
    ['museo-nacional-de-arte-mexico', 'Museo Nacional de Arte', 'National Museum of Art Mexico'],
  ].map(([slug, title, en]) =>
    row(slug as string, 'ORGANIZATION', title as string, en as string, 'institutions'),
  ),
  ...[
    ['alejandria', 'Alejandría', 'Alexandria'],
    ['cordoba', 'Córdoba', 'Córdoba'],
    ['toledo-espanol', 'Toledo', 'Toledo'],
    ['praga', 'Praga', 'Prague'],
    ['zurich', 'Zúrich', 'Zurich'],
    ['weimar', 'Weimar', 'Weimar'],
    ['lagos', 'Lagos', 'Lagos'],
    ['johannesburgo', 'Johannesburgo', 'Johannesburg'],
    ['hanoi', 'Hanói', 'Hanoi'],
    ['mumbai', 'Bombay', 'Mumbai'],
    ['sao-paulo', 'São Paulo', 'São Paulo'],
    ['buenos-aires', 'Buenos Aires', 'Buenos Aires'],
    ['la-habana', 'La Habana', 'Havana'],
  ]
    .concat([
      ['nuremberg', 'Núremberg', 'Nuremberg'],
      ['antwerp', 'Amberes', 'Antwerp'],
      ['napoles', 'Nápoles', 'Naples'],
      ['bruselas', 'Bruselas', 'Brussels'],
    ])
    .map(([slug, title, en]) =>
      row(slug as string, 'PLACE', title as string, en as string, 'places'),
    ),
  ...[
    ['perspectiva-lineal', 'Perspectiva lineal', 'Linear perspective'],
    ['iconografia', 'Iconografía', 'Iconography'],
    ['sublime', 'Sublime', 'Sublime'],
    ['melancolia', 'Melancolía', 'Melancholy'],
    ['archivo', 'Archivo', 'Archive'],
    ['espectaculo', 'Espectáculo', 'Spectacle'],
    ['domesticidad', 'Domesticidad', 'Domesticity'],
    ['migracion', 'Migración', 'Migration'],
    ['exilio', 'Exilio', 'Exile'],
    ['ecologia', 'Ecología', 'Ecology'],
    ['materialidad', 'Materialidad', 'Materiality'],
    ['trabajo-industrial', 'Trabajo industrial', 'Industrial labor'],
    ['educacion', 'Educación', 'Education'],
    ['revolucion-industrial', 'Revolución industrial', 'Industrial Revolution'],
    ['esclavitud', 'Esclavitud', 'Slavery'],
    ['diaspora', 'Diáspora', 'Diaspora'],
    ['comunidad', 'Comunidad', 'Community'],
    ['cuidado', 'Cuidado', 'Care'],
  ].map(([slug, title, en]) =>
    row(slug as string, 'CONCEPT', title as string, en as string, 'cross-period concepts'),
  ),
];

const artistContext: Array<[string, string, string]> = [
  ['giotto', 'gotico', 'florencia'],
  ['jan-van-eyck', 'renacimiento-nordico', 'amsterdam'],
  ['albrecht-durer', 'renacimiento-nordico', 'nuremberg'],
  ['pieter-bruegel', 'renacimiento-nordico', 'amsterdam'],
  ['peter-paul-rubens', 'barroco', 'antwerp'],
  ['artemisia-gentileschi', 'barroco', 'roma'],
  ['jose-de-ribera', 'barroco', 'napoles'],
  ['bartolome-esteban-murillo', 'barroco', 'madrid'],
  ['canaletto', 'rococo', 'venecia'],
  ['william-blake', 'romanticismo', 'londres'],
  ['jmw-turner', 'romanticismo', 'londres'],
  ['john-constable', 'romanticismo', 'londres'],
  ['rosa-bonheur', 'realismo', 'paris'],
  ['berthe-morisot', 'impresionismo', 'paris'],
  ['mary-cassatt', 'impresionismo', 'paris'],
  ['odilon-redon', 'simbolismo', 'paris'],
  ['gustav-klimt', 'art-nouveau', 'viena'],
  ['egon-schiele', 'expresionismo', 'viena'],
  ['ernst-ludwig-kirchner', 'expresionismo', 'berlin'],
  ['paul-klee', 'bauhaus-movement', 'weimar'],
  ['sonia-delaunay', 'orfismo', 'paris'],
  ['el-lissitzky', 'constructivismo', 'moscu'],
  ['hannah-hoch', 'dadaismo', 'berlin'],
  ['rene-magritte', 'surrealismo', 'bruselas'],
  ['max-ernst', 'surrealismo', 'paris'],
  ['meret-oppenheim', 'surrealismo', 'paris'],
  ['alexander-calder', 'surrealismo', 'paris'],
  ['constantin-brancusi', 'abstraccion', 'paris'],
  ['eva-hesse', 'minimalismo', 'nueva-york'],
  ['donald-judd', 'minimalismo', 'nueva-york'],
  ['sol-lewitt', 'arte-conceptual', 'nueva-york'],
  ['agnes-martin', 'minimalismo', 'nueva-york'],
  ['cindy-sherman', 'fotografia', 'nueva-york'],
  ['carrie-mae-weems', 'fotografia', 'nueva-york'],
  ['shirin-neshat', 'arte-conceptual', 'nueva-york'],
  ['el-anatsui', 'arte-africano', 'lagos'],
  ['william-kentridge', 'arte-africano', 'johannesburgo'],
  ['theaster-gates', 'arte-conceptual', 'nueva-york'],
  ['tarsila-do-amaral', 'muralismo-mexicano', 'sao-paulo'],
  ['wifredo-lam', 'surrealismo', 'la-habana'],
  ['remedios-varo', 'surrealismo', 'ciudad-de-mexico'],
  ['david-alfaro-siqueiros', 'muralismo-mexicano', 'ciudad-de-mexico'],
];
export const artistRelations: FoundationalRelation[] = artistContext.flatMap(
  ([person, movement, place]) => [
    relation(person, movement, 'BELONGS_TO_MOVEMENT'),
    relation(person, place, 'LOCATED_IN'),
  ],
);

const workContext: Array<[string, string, string]> = [
  ['mezquita-azul', 'arte-islamico', 'religion'],
  ['palacio-de-versailles', 'rococo', 'poder'],
  ['canaletto-gran-canal', 'canaletto', 'rococo'],
  ['vapor-y-nubes-de-steam-boat', 'jmw-turner', 'romanticismo'],
  ['la-clase-de-danza', 'edgar-degas', 'impresionismo'],
  ['el-barco-de-esclavos', 'jmw-turner', 'violencia'],
  ['el-beso-klimt', 'gustav-klimt', 'art-nouveau'],
  ['retrato-de-adele-bloch-bauer', 'gustav-klimt', 'art-nouveau'],
  ['autorretrato-con-collar-de-espinas', 'frida-kahlo', 'muralismo-mexicano'],
  ['el-hijo-del-hombre', 'rene-magritte', 'surrealismo'],
  ['lobster-telephone', 'salvador-dali', 'surrealismo'],
  ['objeto-para-ser-destruido', 'meret-oppenheim', 'surrealismo'],
  ['mobile-calder-rojo', 'alexander-calder', 'surrealismo'],
  ['obra-de-arte-en-el-tiempo', 'joseph-kosuth', 'arte-conceptual'],
  ['cuerpo-como-archivo', 'cindy-sherman', 'fotografia'],
  ['shibboleth', 'shirin-neshat', 'arte-conceptual'],
  ['tropicalia-obra', 'heli-oiticica', 'arte-conceptual'],
  ['abaporu', 'tarsila-do-amaral', 'muralismo-mexicano'],
  ['la-jungla-lam', 'wifredo-lam', 'surrealismo'],
  ['untitled-film-still-21', 'cindy-sherman', 'fotografia'],
  ['from-here-i-saw-what-happened', 'carrie-mae-weems', 'fotografia'],
];
export const extraRelations: FoundationalRelation[] = artistRelations.concat(
  workContext.flatMap(([work, creator, movement]) => [
    relation(work, creator, 'CREATED_BY'),
    relation(work, movement, 'BELONGS_TO_MOVEMENT'),
  ]),
);
