export const RELATION_TYPES = [
  ['CREATED_BY', 'Creado por', 'Creador de', true, 'authorship', 10],
  ['BELONGS_TO_MOVEMENT', 'Pertenece al movimiento', 'Incluye entidad', true, 'taxonomy', 20],
  ['BELONGS_TO_PERIOD', 'Pertenece al periodo', 'Incluye entidad', true, 'taxonomy', 30],
  ['ABOUT_CONCEPT', 'Explora el concepto', 'Concepto explorado por', true, 'semantic', 40],
  ['LOCATED_IN', 'Ubicado en', 'Ubicación de', true, 'context', 50],
  ['RELATED_TO', 'Relacionado con', 'Relacionado con', false, 'semantic', 60],
  ['ASSOCIATED_WITH', 'Asociado con', 'Asociado con', false, 'semantic', 70],
  ['MENTIONS', 'Menciona', 'Mencionado por', true, 'content', 80],
  ['INSPIRED_BY', 'Inspirado por', 'Inspira a', true, 'influence', 90],
  ['INFLUENCED_BY', 'Influenciado por', 'Influye en', true, 'influence', 100],
  ['PART_OF', 'Forma parte de', 'Incluye', true, 'structure', 110],
  ['DEPICTS', 'Representa', 'Representado en', true, 'semantic', 120],
  ['SIMILAR_TO', 'Similar a', 'Similar a', false, 'semantic', 130],
  ['USES_TECHNIQUE', 'Usa técnica', 'Técnica usada por', true, 'material', 140],
  ['USES_MATERIAL', 'Usa material', 'Material usado por', true, 'material', 150],
  ['HAS_SUBJECT', 'Tiene tema', 'Tema de', true, 'semantic', 160],
  ['CURATED_WITH', 'Curado junto a', 'Curado junto a', false, 'editorial', 170],
] as const;

export const RELATION_TYPE_EN: Record<string, { label: string; inverseLabel: string | null }> = {
  CREATED_BY: { label: 'Created by', inverseLabel: 'Created' },
  BELONGS_TO_MOVEMENT: { label: 'Belongs to movement', inverseLabel: 'Includes entity' },
  BELONGS_TO_PERIOD: { label: 'Belongs to period', inverseLabel: 'Includes entity' },
  ABOUT_CONCEPT: { label: 'Explores concept', inverseLabel: 'Explored by entity' },
  LOCATED_IN: { label: 'Located in', inverseLabel: 'Location of' },
  RELATED_TO: { label: 'Related to', inverseLabel: 'Related to' },
  ASSOCIATED_WITH: { label: 'Associated with', inverseLabel: 'Associated with' },
  MENTIONS: { label: 'Mentions', inverseLabel: 'Mentioned by' },
  INSPIRED_BY: { label: 'Inspired by', inverseLabel: 'Inspires' },
  INFLUENCED_BY: { label: 'Influenced by', inverseLabel: 'Influences' },
  PART_OF: { label: 'Part of', inverseLabel: 'Includes' },
  DEPICTS: { label: 'Depicts', inverseLabel: 'Depicted in' },
  SIMILAR_TO: { label: 'Similar to', inverseLabel: 'Similar to' },
  USES_TECHNIQUE: { label: 'Uses technique', inverseLabel: 'Technique used by' },
  USES_MATERIAL: { label: 'Uses material', inverseLabel: 'Material used by' },
  HAS_SUBJECT: { label: 'Has subject', inverseLabel: 'Subject of' },
  CURATED_WITH: { label: 'Curated with', inverseLabel: 'Curated with' },
};
