import { DeckItem } from '../../shared/ui/entity-deck/entity-deck.types';

export type HomeDeckStarter = {
  id: string;
  surface: 'HOME' | 'RECOMMENDED';
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  titleEn: string;
  subtitleEn: string;
  descriptionEn: string;
  meta: string;
  ctaLabel: string;
  ctaLabelEn: string;
  ctaRoute: string;
  image: string;
  imageWidth: number;
  imageHeight: number;
};

const STARTERS: HomeDeckStarter[] = [
  {
    id: 'home-artwork',
    surface: 'HOME',
    slug: 'artwork',
    title: 'Obras',
    subtitle: 'Artwork',
    titleEn: 'Artworks',
    subtitleEn: 'Key pieces',
    descriptionEn: 'Key pieces for studying form, technique, symbolism and context.',
    description: 'Piezas clave para estudiar forma, técnica, simbolismo y contexto.',
    meta: 'Artwork',
    ctaLabelEn: 'Explore artworks',
    ctaLabel: 'Explorar obras',
    ctaRoute: '/entities/artwork',
    image: '/assets/home/artwork.jpg',
    imageWidth: 736,
    imageHeight: 736,
  },
  {
    id: 'home-article',
    surface: 'HOME',
    slug: 'article',
    title: 'Artículos',
    subtitle: 'Article',
    titleEn: 'Articles',
    subtitleEn: 'Editorial readings',
    descriptionEn: 'Editorial readings, criticism and connections between works, authors and ideas.',
    description: 'Lecturas editoriales, opinión y conexiones entre obras, autores e ideas.',
    meta: 'Article',
    ctaLabelEn: 'Explore articles',
    ctaLabel: 'Explorar artículos',
    ctaRoute: '/entities/article',
    image: '/assets/home/concept.jpg',
    imageWidth: 639,
    imageHeight: 960,
  },
  {
    id: 'home-artist',
    surface: 'HOME',
    slug: 'artist',
    title: 'Artistas',
    subtitle: 'Artist',
    titleEn: 'Artists',
    subtitleEn: 'Visual trajectories',
    descriptionEn: 'Authors, careers, visual obsessions and crossed influences.',
    description: 'Autores, trayectorias, obsesiones visuales e influencias cruzadas.',
    meta: 'Artist',
    ctaLabelEn: 'Explore artists',
    ctaLabel: 'Explorar artistas',
    ctaRoute: '/entities/artist',
    image: '/assets/home/artist.jpg',
    imageWidth: 736,
    imageHeight: 736,
  },
  {
    id: 'home-movement',
    surface: 'HOME',
    slug: 'movement',
    title: 'Movimientos',
    subtitle: 'Movement',
    titleEn: 'Movements',
    subtitleEn: 'Ideas in motion',
    descriptionEn: 'Aesthetic currents and ideas that redefined art history.',
    description: 'Corrientes estéticas e ideas que redefinieron la historia del arte.',
    meta: 'Movement',
    ctaLabelEn: 'Explore movements',
    ctaLabel: 'Explorar movimientos',
    ctaRoute: '/entities/movement',
    image: '/assets/home/movement.jpg',
    imageWidth: 736,
    imageHeight: 977,
  },
  {
    id: 'home-period',
    surface: 'HOME',
    slug: 'period',
    title: 'Períodos',
    subtitle: 'Period',
    titleEn: 'Periods',
    subtitleEn: 'Historical context',
    descriptionEn: 'Historical stages for understanding cultural and visual change.',
    description: 'Etapas históricas para entender cambios culturales y visuales.',
    meta: 'Period',
    ctaLabelEn: 'Explore periods',
    ctaLabel: 'Explorar períodos',
    ctaRoute: '/entities/period',
    image: '/assets/home/period.jpg',
    imageWidth: 600,
    imageHeight: 800,
  },
  {
    id: 'home-concept',
    surface: 'HOME',
    slug: 'concept',
    title: 'Conceptos',
    subtitle: 'Concept',
    titleEn: 'Concepts',
    subtitleEn: 'Reading keys',
    descriptionEn: 'Foundational ideas for reading works and relationships with more clarity.',
    description: 'Ideas fundamentales para leer obras y relaciones con más claridad.',
    meta: 'Concept',
    ctaLabelEn: 'Explore concepts',
    ctaLabel: 'Explorar conceptos',
    ctaRoute: '/entities/concept',
    image: '/assets/home/concept.jpg',
    imageWidth: 639,
    imageHeight: 960,
  },
  {
    id: 'home-place',
    surface: 'HOME',
    slug: 'place',
    title: 'Lugares',
    subtitle: 'Place',
    titleEn: 'Places',
    subtitleEn: 'Institutional context',
    descriptionEn: 'Museums, collections and spaces that anchor works, movements and public memory.',
    description: 'Museos, colecciones y espacios que anclan obras, movimientos y memoria pública.',
    meta: 'Place',
    ctaLabelEn: 'Explore places',
    ctaLabel: 'Explorar lugares',
    ctaRoute: '/entities/place',
    image: '/assets/home/museum-room.jpg',
    imageWidth: 736,
    imageHeight: 981,
  },
  {
    id: 'recommended-artwork',
    surface: 'RECOMMENDED',
    slug: 'recommended-artwork',
    title: 'Obras esenciales',
    subtitle: 'Staff Pick',
    titleEn: 'Essential artworks',
    subtitleEn: 'Staff Pick',
    descriptionEn: 'A curated selection to enter JANO through key works and strong connections.',
    description: 'Una selección curada para entrar a Jano por piezas clave y conexiones fuertes.',
    meta: 'Curated List',
    ctaLabelEn: 'View selection',
    ctaLabel: 'Ver selección',
    ctaRoute: '/entities/artwork',
    image: '/assets/home/artwork.jpg',
    imageWidth: 736,
    imageHeight: 736,
  },
  {
    id: 'recommended-artist',
    surface: 'RECOMMENDED',
    slug: 'recommended-artist',
    title: 'Artistas para empezar',
    subtitle: 'Staff Pick',
    titleEn: 'Artists to start with',
    subtitleEn: 'Staff Pick',
    descriptionEn: 'Foundational authors for understanding styles, ruptures and influences.',
    description: 'Autores fundamentales para entender estilos, rupturas e influencias.',
    meta: 'Curated List',
    ctaLabelEn: 'Explore artists',
    ctaLabel: 'Explorar artistas',
    ctaRoute: '/entities/artist',
    image: '/assets/home/artist.jpg',
    imageWidth: 736,
    imageHeight: 736,
  },
  {
    id: 'recommended-movement',
    surface: 'RECOMMENDED',
    slug: 'recommended-movement',
    title: 'Movimientos imprescindibles',
    subtitle: 'Staff Pick',
    titleEn: 'Essential movements',
    subtitleEn: 'Staff Pick',
    descriptionEn: 'Movements that reorganized vision and changed art history.',
    description: 'Corrientes que reorganizaron la mirada y cambiaron la historia del arte.',
    meta: 'Curated List',
    ctaLabelEn: 'Explore movements',
    ctaLabel: 'Explorar movimientos',
    ctaRoute: '/entities/movement',
    image: '/assets/home/movement.jpg',
    imageWidth: 736,
    imageHeight: 977,
  },
  {
    id: 'recommended-period',
    surface: 'RECOMMENDED',
    slug: 'recommended-period',
    title: 'Períodos clave',
    subtitle: 'Staff Pick',
    titleEn: 'Key periods',
    subtitleEn: 'Staff Pick',
    descriptionEn: 'Historical stages to orient yourself quickly inside the archive.',
    description: 'Etapas históricas para orientarte rápido dentro del archivo.',
    meta: 'Curated List',
    ctaLabelEn: 'Explore periods',
    ctaLabel: 'Explorar períodos',
    ctaRoute: '/entities/period',
    image: '/assets/home/period.jpg',
    imageWidth: 600,
    imageHeight: 800,
  },
  {
    id: 'recommended-concept',
    surface: 'RECOMMENDED',
    slug: 'recommended-concept',
    title: 'Conceptos base',
    subtitle: 'Staff Pick',
    titleEn: 'Core concepts',
    subtitleEn: 'Staff Pick',
    descriptionEn: 'Terms and ideas for reading works, artists and relationships better.',
    description: 'Términos e ideas para leer mejor obras, artistas y relaciones.',
    meta: 'Curated List',
    ctaLabelEn: 'Explore concepts',
    ctaLabel: 'Explorar conceptos',
    ctaRoute: '/entities/concept',
    image: '/assets/home/concept.jpg',
    imageWidth: 639,
    imageHeight: 960,
  },
];

export const HOME_DECK_STARTERS = STARTERS;
export const HOME_FALLBACK_STARTERS = STARTERS.filter((starter) => starter.surface === 'HOME');
export const RECOMMENDED_FALLBACK_STARTERS = STARTERS.filter((starter) => starter.surface === 'RECOMMENDED');

export function starterToDeckItem(starter: HomeDeckStarter): DeckItem {
  return {
    id: starter.id,
    eyebrow: starter.subtitle,
    title: starter.title,
    description: starter.description,
    meta: starter.meta,
    cta: `${starter.ctaLabel} →`,
    image: starter.image,
    imageWidth: starter.imageWidth,
    imageHeight: starter.imageHeight,
    ctaRoute: starter.ctaRoute,
  };
}
