const fs=require('node:fs'),crypto=require('node:crypto');const {PrismaService}=require('/app/backend/api/dist/src/prisma/prisma.service.js');const {CanonicalPromotionService}=require('/app/backend/api/dist/src/research/canonical-promotion.service.js');
const projectId='cmtoojmz10000k9ss84uo6gl9',root=process.env.WAVE_ROOT||'/app';const plan=JSON.parse(fs.readFileSync(`${root}/artifacts/feed-wave-002-final-apply-plan.json`));const review=JSON.parse(fs.readFileSync(`${root}/artifacts/feed-wave-002-review-summary.json`));
const newEntities={
'W002-E001':['Mario García Torres','ARTIST'],'W002-E009':['Judith Baca','ARTIST'],'W002-E010':['Black Mountain College Museum + Arts Center','ORGANIZATION'],'W002-E011':['THINKING AHEAD: Progressive Design + Black Mountain College','EVENT'],'W002-E013':['The Quick and the Dead','EVENT'],'W002-E015':['John Cage','PERSON'],'W002-E017':['The Last Picture Show: Artists Using Photography, 1960-1982','EVENT'],'W002-E024':['Jim Hodges','ARTIST'],'W002-E027':['Lucy Lippard','PERSON'],'W002-E028':['Six Years','TEXT'],'W002-E029':['Revolución de julio de 1830','EVENT']};
const target={'W002-K001':'W002-E001','W002-K003':'cmsvvxisg00sp85sj9035nrbd','W002-K006':'W002-E001','W002-K007':'W002-E009','W002-K008':'W002-E009','W002-K013':'cmsvvxiy500w485sjaswn4h4o','W002-K017':'cmsvvxhgm002r85sjdntcbn33','W002-K020':'W002-E024','W002-K026':'cmsvvxj8a012s85sjedihcwi5','W002-K027':'cmsvvxj8a012s85sjedihcwi5','W002-K028':'cmsvvxiy500w485sjaswn4h4o','W002-R010':'W002-E015','W002-R018':'W002-E027','W002-R019':'W002-E028','W002-R022':'cmsvvxiy500w485sjaswn4h4o','W002-R025':'cmsvvxj8a012s85sjedihcwi5'};
const approvedClaims=['W002-K001','W002-K003','W002-K006','W002-K007','W002-K008','W002-K013','W002-K017','W002-K020','W002-K026','W002-K027','W002-K028'];
const assertionItems=['W002-R010','W002-R018','W002-R019','W002-R022','W002-R025'];
function items(){return new Map(review.batches.flatMap(b=>b.items).map(x=>[x.id,x]));}
(async()=>{const db=new PrismaService();const promo=new CanonicalPromotionService(db);try{
 const counts=async()=>({entities:await db.entity.count(),relations:await db.relation.count(),assertions:await db.canonicalAssertion.count(),sourceRefs:await db.sourceRef.count(),citations:await db.citation.count()});
 const before=await counts();if(!((before.entities===813&&before.relations===1388&&before.assertions===24&&before.sourceRefs===850&&before.citations===1411)||(before.entities===824&&before.relations===1388&&before.assertions===40&&before.sourceRefs===866&&before.citations===1427)))throw Error('PRE_APPLY_DRIFT '+JSON.stringify(before));if(plan.humanReviewComplete!==true||plan.undecidedLogicalItems!==0)throw Error('REVIEW_NOT_COMPLETE');
 const it=items();const entityIds={};const created=[];const resolved=[];
 // exact duplicate/type check and create through the same editorial draft-record shape used by EntityEditorialService
 for(const [rid,[title,type]] of Object.entries(newEntities)){const found=await db.entity.findMany({where:{title},select:{id:true,title:true,type:true,slug:true}});const compatible=found.filter(x=>x.type===type);if(compatible.length>1)throw Error('DUPLICATE_AMBIGUITY '+rid);if(compatible.length===1){entityIds[rid]=compatible[0].id;resolved.push({reviewId:rid,canonicalEntityId:compatible[0].id,classification:'RESOLVE_TO_EXISTING'});continue;}if(found.length)throw Error('TYPE_COLLISION '+rid);const td=await db.entityTypeDefinition.findUnique({where:{key:type},select:{baseKind:true}});if(!td)throw Error('TYPE_UNAVAILABLE '+type);const e=await db.$transaction(async tx=>tx.entity.create({data:{type,kind:td.baseKind,title,slug:'_wave002-'+crypto.createHash('sha1').update(rid).digest('hex').slice(0,16),status:'PUBLISHED',translations:{create:{locale:'es',title}}},select:{id:true,title:true,type:true,slug:true}}));entityIds[rid]=e.id;created.push({reviewId:rid,...e,classification:'CREATE_NEW'});}
 const canonicalMap=new Map((await db.entity.findMany({select:{id:true,title:true,type:true}})).map(e=>[e.id,e]));for(const k of Object.keys(target)){if(target[k].startsWith('W002-')){const id=entityIds[target[k]];if(!id)throw Error('MISSING_TARGET '+k);target[k]=id;}if(!canonicalMap.has(target[k]))throw Error('TARGET_NOT_FOUND '+k);}
 const operations=[];for(const id of approvedClaims.concat(assertionItems)){const x=it.get(id);if(!x)throw Error('ITEM_MISSING '+id);const s=(x.supports||[])[0];if(!s)throw Error('SUPPORT_MISSING '+id);const evidence=await db.researchEvidence.findUnique({where:{id:s.evidenceId},select:{id:true,sourceId:true,libraryExcerptId:true}});if(!evidence||evidence.sourceId!==s.sourceId)throw Error('EVIDENCE_MISMATCH '+id);const prop=x.proposition||x.rawProposition||x.rawProposition;const quote=s.exactSupport||s.exactEvidence;if(!prop||!quote)throw Error('PROPOSITION_MISSING '+id);operations.push({kind:'ASSERTION',entityId:target[id],sourceId:s.sourceId,evidenceId:s.evidenceId,excerptId:s.excerptId,quote,proposition:prop,dimension:'KNOWLEDGE',targetStatus:'TARGET_CONFIRMED'});}
 const result=await promo.apply(operations);const after=await counts();if(after.entities<before.entities||after.relations!==before.relations||after.assertions<before.assertions)throw Error('POST_APPLY_COUNT_ERROR');
 const out={status:'SUCCESS',projectId,before,after,entitiesCreated:created,entitiesResolvedExisting:resolved,assertionsApplied:result,relationsCreated:0,operations:operations.map((o,i)=>({reviewId:approvedClaims.concat(assertionItems)[i],...o})),timestamp:new Date().toISOString()};fs.writeFileSync(`${root}/artifacts/feed-wave-002-final-apply-result.json`,JSON.stringify(out,null,2));console.log(JSON.stringify({status:'SUCCESS',before,after,entitiesCreated:created.length,assertions:result.length}));
}finally{await db.onModuleDestroy()}})().catch(e=>{console.error(e);process.exitCode=1});
