ALTER TABLE "Media"
ADD COLUMN "focalX" DOUBLE PRECISION,
ADD COLUMN "focalY" DOUBLE PRECISION;

ALTER TABLE "EntityMedia"
ADD COLUMN "cropExplorer3d" JSONB,
ADD COLUMN "cropList" JSONB,
ADD COLUMN "cropDetail" JSONB,
ADD COLUMN "cropPreview" JSONB;
