BEGIN;

-- BATCH_EDITORIAL_002: summary + essay, bilingual, grounded in published
-- assertions, structured facts, eligible relations and public SourceRefs.
CREATE TEMP TABLE editorial_batch_002 (
  id text PRIMARY KEY,
  summary_es text NOT NULL,
  essay_es text NOT NULL,
  summary_en text NOT NULL,
  essay_en text NOT NULL
);

INSERT INTO editorial_batch_002 VALUES
('cmtptpmhz0000gxss1r1ra4ao',
 'Mario García Torres es un artista cuya práctica investiga la historia del arte conceptual y recupera relatos poco visibles en las versiones oficiales. Su trabajo combina investigación, memoria y narración para volver a abrir episodios de la historia del arte.',
 '## Investigación y memoria\n\nSegún Walker, la obra de [[_wave002-807694c624b3ebf6|Mario García Torres]] vuelve sobre la historia del arte conceptual para rescatar hechos, testimonios y proyectos poco conocidos. La investigación no funciona aquí como un simple método preparatorio: es una forma de producir nuevas lecturas sobre lo que la historia ha dejado en segundo plano.\n\nLa exposición *Illusion Brought Me Here* lo presenta como investigador y narrador. Esa doble condición ayuda a entender una práctica interesada tanto por los documentos como por las formas en que una historia se cuenta, se conserva y vuelve a circular.',
 'Mario García Torres is an artist whose practice investigates the history of Conceptual art and recovers narratives that official accounts have left obscure. His work brings research, memory, and storytelling together to reopen episodes in art history.',
 '## Research and memory\n\nAccording to Walker, [[_wave002-807694c624b3ebf6|Mario García Torres]] returns to the history of Conceptual art to recover little-known facts, testimonies, and projects. Research is not merely preparatory here: it becomes a way of producing new readings of what art history has pushed into the background.\n\nWalker’s exhibition *Illusion Brought Me Here* presents him as both researcher and storyteller. That double role helps explain a practice concerned not only with documents, but also with the ways a story is told, preserved, and brought back into circulation.'),
('cmsvvxiey00ko85sjzcckqm33',
 'El Tapiz de Bayeux es una obra narrativa medieval que cuenta la aventura de Guillermo el Conquistador en torno a 1066. Su importancia reside en cómo convierte una secuencia histórica de guerra, poder y conquista en una imagen continua, y en su posterior reconocimiento como Memoria del Mundo de la UNESCO.',
 '## Una historia en imágenes\n\nEl [[tapiz-de-bayeux|Tapiz de Bayeux]] narra la aventura épica de Guillermo el Conquistador en 1066. La obra organiza acontecimientos históricos en una secuencia visual continua, donde la conquista aparece ligada a la autoridad, la violencia y la construcción de una memoria política.\n\nSu relevancia no depende sólo de lo que cuenta, sino de la forma en que hace visible una historia. La inscripción de la pieza en el programa Memoria del Mundo de la UNESCO señala también la importancia de su conservación y de su valor como testimonio cultural.',
 'The Bayeux Tapestry is a medieval narrative work that recounts the adventure of William the Conqueror around 1066. Its importance lies in turning a sequence of war, power, and conquest into a continuous image, and in its later recognition as part of UNESCO’s Memory of the World.',
 '## History in images\n\nThe [[tapiz-de-bayeux|Bayeux Tapestry]] recounts the epic adventure of William the Conqueror in 1066. It organizes historical events as a continuous visual sequence, linking conquest to authority, violence, and the construction of political memory.\n\nIts significance lies not only in what it narrates, but in the way it makes history visible. Its inclusion in UNESCO’s Memory of the World programme also points to the importance of its preservation and its value as a cultural record.'),
('cmsvvxhez001x85sjnaghwwqx',
 'El Neoclasicismo fue una forma particularmente pura del clasicismo que surgió hacia 1750 y se desarrolló en el arte, la arquitectura y el diseño del siglo XVIII. La recuperación de la Antigüedad, la influencia de Winckelmann y el diálogo posterior con el Romanticismo ayudan a situar su importancia histórica.',
 '## Antigüedad y razón formal\n\nEl [[neoclasicismo|Neoclasicismo]] surgió hacia 1750 como una forma particularmente pura del clasicismo. Su desarrollo estuvo ligado a un intenso florecimiento del interés por el arte antiguo en el siglo XVIII, tanto en las artes visuales como en la arquitectura y el diseño.\n\nLa publicación, en 1764, de una historia muy influyente del arte antiguo por Johann Joachim Winckelmann formó parte de ese contexto. El movimiento no fue una simple copia del pasado: convirtió la Antigüedad en un lenguaje moderno de orden, referencia histórica y autoridad cultural. Su relación con el [[romanticismo|Romanticismo]] permite reconocer dos respuestas distintas a la herencia clásica.',
 'Neoclassicism was a particularly pure form of classicism that emerged around 1750 and developed across eighteenth-century art, architecture, and design. The recovery of antiquity, Winckelmann’s influence, and the movement’s later dialogue with Romanticism help explain its historical importance.',
 '## Antiquity and formal order\n\n[[neoclasicismo|Neoclassicism]] emerged around 1750 as a particularly pure form of classicism. Its development was part of an intense eighteenth-century flourishing of interest in ancient art, across visual art, architecture, and design.\n\nThe publication in 1764 of Johann Joachim Winckelmann’s highly influential history of ancient art belonged to this context. The movement was not simply a copy of the past: it turned antiquity into a modern language of order, historical reference, and cultural authority. Its relationship with [[romanticismo|Romanticism]] reveals two different responses to the classical inheritance.'),
('cmsvvxisg00sp85sj9035nrbd',
 'Sol LeWitt fue un artista estadounidense, nacido en 1928 y fallecido en 2007, cuya obra ocupa un lugar central en el desarrollo del arte conceptual. Para él, la planificación y las decisiones podían preceder a la realización material de la obra.',
 '## La idea como estructura\n\n[[sol-lewitt|Sol LeWitt]] fue una voz pionera del [[arte-conceptual|arte conceptual]]. Su propuesta desplazó la atención desde la ejecución manual hacia la planificación: cuando el artista trabaja con una forma conceptual, las decisiones se toman antes y la idea actúa como la máquina que produce la obra.\n\nEste planteamiento no elimina la materialidad. Cambia el lugar que ocupa dentro del proceso artístico y vuelve visible la relación entre instrucciones, decisiones y realización. Por eso su práctica sigue siendo importante para entender cómo una obra puede existir como proyecto, sistema o conjunto de reglas.',
 'Sol LeWitt was an American artist, born in 1928 and deceased in 2007, whose work occupies a central place in the development of Conceptual art. For him, planning and decisions could come before the material execution of a work.',
 '## The idea as structure\n\n[[sol-lewitt|Sol LeWitt]] was a pioneering voice in [[arte-conceptual|Conceptual art]]. His proposal shifted attention from manual execution to planning: when an artist uses a conceptual form, decisions are made beforehand and the idea becomes the machine that produces the work.\n\nThis approach does not remove materiality. It changes its place within the artistic process and makes the relationship between instructions, decisions, and execution visible. That is why his practice remains important for understanding how a work can exist as a project, a system, or a set of rules.'),
('cmsvvxhkg004u85sjoq4l52tb',
 'Cuerpo es un concepto recurrente en prácticas artísticas como la performance, el arte conceptual y el vídeo. Permite leer cómo la presencia física, la identidad, la representación y la experiencia se convierten en materia de la obra.',
 '## El cuerpo como materia artística\n\nEl [[cuerpo|cuerpo]] aparece como tema recurrente en prácticas que incluyen la performance, el arte conceptual y el vídeo. No se trata únicamente de representar una figura humana: el cuerpo puede actuar, ocupar un espacio, registrar una experiencia o convertirse en el lugar donde se negocian identidad y memoria.\n\nLas relaciones de lectura de este concepto atraviesan obras y periodos muy distintos. Esa amplitud es precisamente lo que lo hace útil: permite comparar imágenes, acciones y objetos sin reducirlos a una sola idea de lo humano.',
 'Body is a recurring concept in practices such as performance, Conceptual art, and video art. It makes it possible to read how physical presence, identity, representation, and experience become material for a work.',
 '## The body as artistic material\n\nThe [[cuerpo|body]] appears as a recurring theme in practices that include performance, Conceptual art, and video. It is not only a matter of representing a human figure: the body can act, occupy a space, record an experience, or become the place where identity and memory are negotiated.\n\nThe concept’s reading relations cross very different works and periods. That breadth is precisely what makes it useful: it allows images, actions, and objects to be compared without reducing them to a single idea of the human.'),
('cmtptpmin000egxss601d3qxo',
 'Jim Hodges es un artista cuya trayectoria incluye un momento decisivo de cambio desde la pintura hacia el dibujo. Según su recuerdo citado por Whitney, ese desplazamiento le ayudó a buscar una voz propia en Nueva York durante los años ochenta.',
 '## Encontrar una voz\n\nSegún el recuerdo de [[_wave002-499508459a2cf989|Jim Hodges]] citado por el Whitney, durante los años ochenta le resultaba difícil encontrar su propia voz en la pintura. Podía imitar referencias históricas, pero no encontraba en ese medio una forma de llegar a sí mismo.\n\nPor eso dejó temporalmente los lienzos y recurrió al dibujo, especialmente al carbón y el papel. El cambio de materiales fue un momento decisivo: modificó su idea de lo que significaba ser artista y dio forma a una práctica entendida como búsqueda.',
 'Jim Hodges is an artist whose practice includes a decisive shift from painting to drawing. In a recollection quoted by the Whitney, that change helped him search for his own voice in New York during the 1980s.',
 '## Finding a voice\n\nIn a recollection by [[_wave002-499508459a2cf989|Jim Hodges]] quoted by the Whitney, he describes struggling in the 1980s to find his own voice in painting. He could imitate historical references, but could not find a way to himself through that medium.\n\nHe therefore set aside his canvases for a time and turned to drawing, especially charcoal and paper. The change of materials became decisive: it altered his sense of what it meant to be an artist and shaped a practice understood as a search.'),
('cmsvvxik600np85sjz1rz8irp',
 'Detrás de la estación Saint-Lazare es una fotografía de Henri Cartier-Bresson creada en 1932. La imagen pertenece a una tradición de fotografía moderna atenta al instante, al movimiento y a la relación entre memoria y experiencia urbana.',
 '## El instante urbano\n\nDetrás de la estación Saint-Lazare fue creada por [[henri-cartier-bresson|Henri Cartier-Bresson]] en 1932. Su relación con la fotografía y la memoria sitúa la obra en el problema de cómo una imagen puede fijar un momento fugaz de la vida urbana.\n\nLa importancia de la fotografía no depende sólo de registrar un lugar. También está en la tensión entre movimiento y detención: el instante se vuelve visible, pero conserva algo de lo que no puede repetirse.',
 'Behind the Gare Saint-Lazare is a photograph by Henri Cartier-Bresson, made in 1932. The image belongs to a tradition of modern photography attentive to the instant, movement, and the relationship between memory and urban experience.',
 '## The urban instant\n\nBehind the Gare Saint-Lazare was made by [[henri-cartier-bresson|Henri Cartier-Bresson]] in 1932. Its relationship with photography and memory places it within the question of how an image can hold a fleeting moment of urban life.\n\nThe photograph matters as more than a record of a place. Its force also lies in the tension between movement and arrest: the instant becomes visible while retaining something that cannot be repeated.'),
('cmsvvxjo001ca85sjmyaxay76',
 'Divisor es una obra de 1968 de Lygia Pape que la fuente la caracteriza como emblemática dentro de su práctica. Sus relaciones con el arte conceptual, la autoría y la reproducción permiten atender a cómo una obra organiza la circulación de una idea.',
 '## Obra y reproducción\n\nLa fuente caracteriza [[divisor|Divisor]], fechada en 1968, como una obra emblemática de [[lygia-pape|Lygia Pape]]. Ese calificativo pertenece a la fuente y no debe entenderse como una medida absoluta de su importancia.\n\nLa obra se relaciona con el [[arte-conceptual|arte conceptual]], la autoría y la reproducción. Esas conexiones permiten observar cómo el sentido artístico puede depender tanto de una forma visible como de las condiciones que determinan quién la realiza, cómo se repite y cómo se reconoce.',
 'Divisor is a 1968 work by Lygia Pape that its source characterizes as emblematic within her practice. Its relations with Conceptual art, authorship, and reproduction invite attention to how a work organizes the circulation of an idea.',
 '## Work and reproduction\n\nThe source characterizes [[divisor|Divisor]], dated 1968, as an emblematic work in the practice of [[lygia-pape|Lygia Pape]]. That evaluation belongs to the source and should not be treated as an absolute measure of the work’s importance.\n\nThe work is related to [[arte-conceptual|Conceptual art]], authorship, and reproduction. These connections make it possible to see how artistic meaning can depend both on visible form and on the conditions that determine who makes it, how it is repeated, and how it is recognized.'),
('cmsvvxijw00nj85sjfpvlk0sx',
 'El Edificio Bauhaus de Dessau fue construido entre 1925 y 1926, cuando la Bauhaus se trasladó de Weimar a Dessau. Su interés reside en convertir las ideas de la escuela —educación, trabajo y vida moderna— en una forma arquitectónica.',
 '## Una escuela hecha edificio\n\nCuando la [[bauhaus-movement|Bauhaus]] se trasladó de Weimar a Dessau, surgió la oportunidad de construir una nueva sede que expresara arquitectónicamente las ideas de sus miembros. El [[edificio-bauhaus-dessau|Edificio Bauhaus de Dessau]], levantado entre 1925 y 1926, convierte ese programa educativo en espacio.\n\nLa obra importa porque muestra que la arquitectura no era un escenario neutral para la Bauhaus. El edificio relaciona enseñanza, trabajo industrial, colaboración y vida cotidiana, y hace visible la aspiración de unir diseño, técnica y educación.',
 'The Bauhaus Building in Dessau was built between 1925 and 1926, when the Bauhaus moved from Weimar to Dessau. Its importance lies in turning the school’s ideas about education, work, and modern life into architectural form.',
 '## A school made into a building\n\nWhen the [[bauhaus-movement|Bauhaus]] moved from Weimar to Dessau, a new opportunity arose: to build a headquarters that would express the school’s ideas in architectural form. The [[edificio-bauhaus-dessau|Bauhaus Building in Dessau]], built between 1925 and 1926, turns an educational programme into space.\n\nThe building matters because architecture was not a neutral setting for the Bauhaus. It connects teaching, industrial work, collaboration, and everyday life, making visible the ambition to bring design, technology, and education together.'),
('cmsvvxjpm01d785sjen4u75ng',
 'Faces and Phases es una serie de Zanele Muholi que el registro de The Walther Collection presenta como un conjunto de 15 impresiones de gelatina de plata fechado entre 2007 y 2013. La serie vincula retrato, fotografía y memoria.',
 '## Retrato y memoria\n\nEl registro de The Walther Collection presenta [[faces-and-phases|Faces and Phases]] de [[zanele-muholi|Zanele Muholi]] como un conjunto de 15 impresiones de gelatina de plata fechado entre 2007 y 2013. La descripción se mantiene en el ámbito del registro de la colección.\n\nSus relaciones con el retrato, el cuerpo, la fotografía y la memoria permiten entender la serie como una forma de hacer visibles presencias y experiencias. El retrato no aparece sólo como identificación individual: también participa en la construcción de una memoria colectiva.',
 'Faces and Phases is a series by Zanele Muholi that The Walther Collection record presents as 15 gelatin-silver prints dated 2007–2013. The series brings portraiture, photography, and memory together.',
 '## Portraiture and memory\n\nThe Walther Collection record presents [[faces-and-phases|Faces and Phases]] by [[zanele-muholi|Zanele Muholi]] as 15 gelatin-silver prints dated 2007–2013. This wording remains within the scope of the collection record.\n\nIts relations with portraiture, the body, photography, and memory make it possible to understand the series as a way of making presences and experiences visible. The portrait is not only a form of individual identification; it also participates in the construction of collective memory.'),
('cmsvvxhf5002085sjoipo63py',
 'El Romanticismo fue un movimiento artístico y literario en uso desde comienzos del siglo XIX, asociado a un nuevo interés por la psicología humana, la expresión del sentimiento personal y el mundo natural. Su diversidad se aprecia en el diálogo entre naturaleza, historia, revolución y experiencia subjetiva.',
 '## Sentimiento, naturaleza e historia\n\nA comienzos del siglo XIX, el término [[romanticismo|Romanticismo]] se empleaba para describir un movimiento artístico y literario distinguido por su interés renovado en la psicología humana, la expresión del sentimiento personal y el mundo natural. No designa una única fórmula visual, sino un campo de respuestas a las transformaciones de la modernidad.\n\nSus relaciones con [[naturaleza|naturaleza]], revolución, historia y obras de Goya, Delacroix, Turner o Constable muestran esa amplitud. El movimiento importa porque convirtió la experiencia subjetiva y la fuerza de lo natural en asuntos históricos y culturales de primer orden.',
 'By the early nineteenth century, Romanticism was used to describe an artistic and literary movement distinguished by new interest in human psychology, personal feeling, and the natural world. Its diversity appears in the dialogue between nature, history, revolution, and subjective experience.',
 '## Feeling, nature, and history\n\nBy the early nineteenth century, [[romanticismo|Romanticism]] was used to describe an artistic and literary movement distinguished by renewed interest in human psychology, personal feeling, and the natural world. It does not name a single visual formula, but a field of responses to the transformations of modernity.\n\nIts relations with [[naturaleza|nature]], revolution, history, and works by Goya, Delacroix, Turner, and Constable show that breadth. The movement matters because it made subjective experience and the power of the natural world central historical and cultural subjects.'),
('cmtptpmij000agxssmqcy841u',
 'John Cage aparece en una fuente del Black Mountain College Museum en el contexto de un evento que reunía música, cine, danza, ruido y vida cotidiana. El episodio muestra la importancia de los formatos colectivos y experimentales para entender la cultura artística de Black Mountain College.',
 '## Un acontecimiento expandido\n\nUna fuente del [[black-mountain-college|Black Mountain College]] Museum + Arts Center registra un evento en el que [[_wave002-02ab0af431ef65b2|John Cage]] habló sobre la relación entre música y budismo zen mientras se proyectaba una película, Merce Cunningham bailaba y sonaban un piano preparado, silbatos y discos.\n\nEl interés del episodio está en su mezcla de disciplinas y situaciones. La música no aparece aislada, sino integrada en una experiencia colectiva donde la conversación, el movimiento, el ruido y lo cotidiano forman parte del acontecimiento.',
 'John Cage appears in a Black Mountain College Museum source in the context of an event that brought together music, film, dance, noise, and everyday life. The episode shows why collective and experimental formats matter for understanding Black Mountain College’s artistic culture.',
 '## An expanded event\n\nA source from the [[black-mountain-college|Black Mountain College]] Museum + Arts Center records an event in which [[_wave002-02ab0af431ef65b2|John Cage]] spoke about the relationship between music and Zen Buddhism while a film was shown, Merce Cunningham danced, and a prepared piano, whistles, and records sounded.\n\nThe episode matters because of its mixture of disciplines and situations. Music does not appear in isolation, but as part of a collective experience in which conversation, movement, noise, and the everyday become elements of the event.'),
('cmtptpmip000ggxssoyqavhne',
 'Lucy Lippard fue una escritora y comisaria cuya publicación Six Years catalogó y describió el desarrollo del arte conceptual. El libro ayudó a reunir obras, artistas y colectivos dentro de una historia crítica de las prácticas conceptuales.',
 '## Escribir la historia del arte conceptual\n\n[[lucy-lippard|Lucy Lippard]] creó *Six Years*, una publicación que, según el Walker Art Center, culminó una serie de exposiciones y ensayos y reunió sus escritos sobre el desarrollo del [[arte-conceptual|arte conceptual]]. El libro no sólo enumera obras: también introduce a los lectores en las prácticas de artistas y colectivos.\n\nSu importancia está en la relación entre crítica, exposición y memoria histórica. Lippard ayudó a dar forma a un campo que todavía estaba definiendo sus términos y sus protagonistas.',
 'Lucy Lippard was a writer and curator whose publication *Six Years* catalogued and described the development of Conceptual art. The book helped bring artists, works, and collectives into a critical history of conceptual practices.',
 '## Writing the history of Conceptual art\n\n[[lucy-lippard|Lucy Lippard]] created *Six Years*, a publication that, according to the Walker Art Center, culminated a series of exhibitions and essays and gathered her writings on the development of [[arte-conceptual|Conceptual art]]. The book does more than list works: it introduces readers to the practices of artists and collectives.\n\nIts importance lies in the relationship between criticism, exhibition-making, and historical memory. Lippard helped shape a field that was still defining its terms and its protagonists.'),
('cmtptpmis000igxssmf1ps38f',
 'Six Years es un texto fundamental del periodo del arte conceptual y una compilación de escritos de Lucy Lippard sobre su desarrollo. Publicado en 1973, reúne y describe obras, artistas y colectivos que estaban redefiniendo la práctica artística.',
 '## Un archivo crítico del conceptualismo\n\n*Six Years* pertenece al periodo del [[arte-conceptual|arte conceptual]]. El Walker Art Center lo describe como una compilación de escritos de [[lucy-lippard|Lucy Lippard]] que catalogó y describió el desarrollo de esas prácticas, al tiempo que introducía a los lectores en las obras de artistas y colectivos.\n\nPublicado en 1973, el texto importa porque construye un mapa crítico de un campo todavía reciente. Su forma de reunir documentación, descripción y argumento participa en la propia historia que intenta explicar.',
 'Six Years is a key text from the period of Conceptual art and a compilation of Lucy Lippard’s writings on its development. Published in 1973, it brings together and describes works, artists, and collectives that were redefining artistic practice.',
 '## A critical archive of Conceptual art\n\n*Six Years* belongs to the period of [[arte-conceptual|Conceptual art]]. The Walker Art Center describes it as a compilation of writings by [[lucy-lippard|Lucy Lippard]] that catalogued and described the development of these practices while introducing readers to the work of artists and collectives.\n\nPublished in 1973, the text matters because it builds a critical map of a still-recent field. Its combination of documentation, description, and argument becomes part of the history it sets out to explain.'),
('cmsvvxiiz00n185sjw6zp49w2',
 'Cuadrado negro es una pintura al óleo sobre lienzo de Kazimir Malévich, fechada en 1915, de 79,5 × 79,5 cm y conservada en la Galería Tretiakov de Moscú. La obra se relaciona con el Suprematismo y con la reducción radical de la imagen a una forma elemental.',
 '## Reducir la pintura a una forma\n\n[[cuadrado-negro|Cuadrado negro]] fue realizado por [[kazimir-malevich|Kazimir Malévich]] en 1915. Es una pintura al óleo sobre lienzo de 79,5 × 79,5 cm, conservada en la Galería Tretiakov de Moscú.\n\nSu relación con el [[suprematismo|Suprematismo]] permite entender la obra como una apuesta por separar la pintura de la obligación de representar objetos reconocibles. El cuadrado no funciona sólo como una figura simple: concentra una discusión sobre qué puede ser una imagen y qué condiciones hacen que una superficie se convierta en pintura.',
 'Black Square is an oil painting on canvas by Kazimir Malevich, dated 1915, measuring 79.5 × 79.5 cm and held by the Tretyakov Gallery in Moscow. The work is associated with Suprematism and with the radical reduction of the image to an elementary form.',
 '## Reducing painting to a form\n\n[[cuadrado-negro|Black Square]] was made by [[kazimir-malevich|Kazimir Malevich]] in 1915. It is an oil painting on canvas measuring 79.5 × 79.5 cm, held by the Tretyakov Gallery in Moscow.\n\nIts relationship with [[suprematismo|Suprematism]] helps explain the work as an attempt to separate painting from the obligation to represent recognizable objects. The square is not only a simple figure: it concentrates a question about what an image can be and what conditions make a surface a painting.'),
('cmsvvxikl00ny85sjt1lqzv9u',
 'Díptico de Marilyn es una pintura de Andy Warhol fechada en 1962, realizada con óleo sobre lienzo y vinculada a la Tate Modern. Su repetición de un retrato convierte la fama, la reproducción y la imagen pública en materia pictórica.',
 '## La imagen repetida\n\n[[diptico-marilyn|Díptico de Marilyn]] fue realizado por [[andy-warhol|Andy Warhol]] en 1962 con óleo sobre lienzo. La obra se relaciona con el Pop Art, la serigrafía, el retrato y la imagen de Marilyn Monroe como figura pública.\n\nLa repetición modifica el estatuto del retrato. La imagen parece multiplicarse y, al mismo tiempo, perder estabilidad: puede leerse como homenaje, producto de consumo o señal de la transformación de una persona en icono.',
 'Marilyn Diptych is a 1962 painting by Andy Warhol, made with oil on canvas and associated with Tate Modern. Its repetition of a portrait turns fame, reproduction, and the public image into pictorial material.',
 '## The repeated image\n\n[[diptico-marilyn|Marilyn Diptych]] was made by [[andy-warhol|Andy Warhol]] in 1962 with oil on canvas. The work is related to Pop Art, screen printing, portraiture, and Marilyn Monroe as a public figure.\n\nRepetition changes the status of the portrait. The image seems to multiply while losing stability: it can be read as homage, consumer product, or a sign of the transformation of a person into an icon.'),
('cmsvvxifi00l085sjugsfayoh',
 'La Gioconda, también conocida como Mona Lisa, es una pintura al óleo sobre tabla de álamo de Leonardo da Vinci, fechada entre 1503 y 1519. Conservada en el Museo del Louvre, se ha convertido en una de las imágenes más reconocibles de la tradición del retrato occidental.',
 '## Un retrato convertido en icono\n\n[[mona-lisa|La Gioconda]], conocida también como Mona Lisa, fue realizada por [[leonardo-da-vinci|Leonardo da Vinci]] entre 1503 y 1519. Es una pintura al óleo sobre tabla de álamo de 77 × 53 cm, conservada en el Museo del Louvre de París.\n\nLa obra importa tanto por su construcción pictórica como por su recepción. El retrato articula cuerpo, belleza y representación, mientras su fama posterior muestra cómo una pintura puede separarse de su contexto original y convertirse en un icono cultural global.',
 'The Mona Lisa, also known as La Gioconda, is an oil painting on poplar panel by Leonardo da Vinci, dated between 1503 and 1519. Held by the Louvre Museum, it has become one of the most recognizable images in the tradition of Western portraiture.',
 '## A portrait turned into an icon\n\n[[mona-lisa|The Mona Lisa]], also known as La Gioconda, was made by [[leonardo-da-vinci|Leonardo da Vinci]] between 1503 and 1519. It is an oil painting on poplar panel measuring 77 × 53 cm, held by the Louvre Museum in Paris.\n\nThe work matters both for its pictorial construction and for its reception. The portrait brings body, beauty, and representation together, while its later fame shows how a painting can become detached from its original context and turn into a global cultural icon.'),
('cmsvvxigo00lp85sjwlacqlkk',
 'La joven de la perla es una pintura al óleo sobre lienzo de Johannes Vermeer, fechada hacia 1665 y conservada en el Mauritshuis de La Haya. Su retrato concentra la atención en la luz, la mirada y la presencia fugitiva de la figura.',
 '## Luz y presencia\n\n[[joven-de-la-perla|La joven de la perla]] fue pintada por [[johannes-vermeer|Johannes Vermeer]] hacia 1665. Es un óleo sobre lienzo de 44,5 × 39 cm, conservado en el Mauritshuis de La Haya.\n\nLa obra se relaciona con el Barroco, la luz, el retrato y la domesticidad. Su fuerza no depende de una narración extensa: una mirada, un giro del cuerpo y el brillo del pendiente bastan para producir una presencia que parece inmediata y, a la vez, inaccesible.',
 'Girl with a Pearl Earring is an oil painting on canvas by Johannes Vermeer, dated around 1665 and held by the Mauritshuis in The Hague. Its portrait concentrates attention on light, gaze, and the fleeting presence of the figure.',
 '## Light and presence\n\n[[joven-de-la-perla|Girl with a Pearl Earring]] was painted by [[johannes-vermeer|Johannes Vermeer]] around 1665. It is an oil painting on canvas measuring 44.5 × 39 cm, held by the Mauritshuis in The Hague.\n\nThe work is related to the Baroque, light, portraiture, and domesticity. Its force does not depend on an extended narrative: a gaze, a turn of the body, and the glint of the earring are enough to create a presence that seems immediate and, at the same time, inaccessible.'),
('cmsvvxihz00mg85sjk879llis',
 'La noche estrellada es una pintura al óleo sobre lienzo de Vincent van Gogh, fechada en 1889 y conservada en el Museum of Modern Art de Nueva York. El paisaje convierte la noche, el movimiento y la naturaleza en una experiencia visual intensa.',
 '## Un paisaje en movimiento\n\n[[noche-estrellada|La noche estrellada]] fue pintada por [[vincent-van-gogh|Vincent van Gogh]] en 1889. Es un óleo sobre lienzo de 73,7 × 92,1 cm, conservado en el Museum of Modern Art de Nueva York.\n\nSu relación con el postimpresionismo, el paisaje, la naturaleza y lo sublime ayuda a comprender la tensión de la obra. El cielo parece moverse como una materia viva, mientras el pueblo y el ciprés ofrecen una escala humana frente a una noche que desborda la observación literal.',
 'The Starry Night is an oil painting on canvas by Vincent van Gogh, dated 1889 and held by the Museum of Modern Art in New York. The landscape turns night, movement, and nature into an intense visual experience.',
 '## A landscape in motion\n\n[[noche-estrellada|The Starry Night]] was painted by [[vincent-van-gogh|Vincent van Gogh]] in 1889. It is an oil painting on canvas measuring 73.7 × 92.1 cm, held by the Museum of Modern Art in New York.\n\nIts relationship with Post-Impressionism, landscape, nature, and the sublime helps explain the work’s tension. The sky seems to move like living material, while the village and cypress provide a human scale against a night that exceeds literal observation.'),
('cmsvvxiik00ms85sjhazvatuz',
 'Las señoritas de Aviñón es una pintura de Pablo Picasso fechada en 1907 y conservada en el Museum of Modern Art de Nueva York. Sus cuerpos angulares y su espacio discontinuo anuncian una ruptura decisiva con las convenciones del retrato y la representación.',
 '## Una ruptura de la representación\n\n[[las-senoritas-de-avignon|Las señoritas de Aviñón]] fue pintada por [[pablo-picasso|Pablo Picasso]] en 1907. Es un óleo sobre lienzo de 243,9 × 233,7 cm, conservado en el Museum of Modern Art de Nueva York.\n\nLa obra se relaciona con el Cubismo, el collage y la naturaleza muerta. Sus figuras angulares y sus planos enfrentados no construyen un espacio estable; obligan a reconsiderar cómo se organiza un cuerpo, cómo se mira una escena y qué significa representar.',
 'Les Demoiselles d’Avignon is a painting by Pablo Picasso, dated 1907 and held by the Museum of Modern Art in New York. Its angular bodies and discontinuous space announce a decisive break with conventions of portraiture and representation.',
 '## A break with representation\n\n[[las-senoritas-de-avignon|Les Demoiselles d’Avignon]] was painted by [[pablo-picasso|Pablo Picasso]] in 1907. It is an oil painting on canvas measuring 243.9 × 233.7 cm, held by the Museum of Modern Art in New York.\n\nThe work is related to Cubism, collage, and still life. Its angular figures and opposed planes do not build a stable space; they force a reconsideration of how a body is organized, how a scene is viewed, and what it means to represent.');

UPDATE "Entity" e SET summary=b.summary_es, content=b.essay_es FROM editorial_batch_002 b WHERE e.id=b.id;
UPDATE "EntityTranslation" t SET "shortDescription"=b.summary_es, essay=b.essay_es, excerpt=b.summary_es FROM editorial_batch_002 b WHERE t."entityId"=b.id AND t.locale='es';
INSERT INTO "EntityTranslation" (id,"entityId",locale,title,"shortDescription",essay,excerpt,"createdAt","updatedAt")
SELECT 'batch002-'||b.id, b.id, 'en', e.title, b.summary_en, b.essay_en, b.summary_en, now(), now()
FROM editorial_batch_002 b JOIN "Entity" e ON e.id=b.id
ON CONFLICT ("entityId",locale) DO UPDATE SET "shortDescription"=excluded."shortDescription", essay=excluded.essay, excerpt=excluded.excerpt, "updatedAt"=now();

-- PostgreSQL stores the prose above with escaped line breaks in SQL literals;
-- normalize them before the public Rich Text resolver reads the content.
UPDATE "Entity" e SET content=replace(e.content, chr(92)||'n', chr(10)) FROM editorial_batch_002 b WHERE e.id=b.id;
UPDATE "EntityTranslation" t SET essay=replace(t.essay, chr(92)||'n', chr(10)) WHERE t."entityId" IN (SELECT id FROM editorial_batch_002) AND t.locale IN ('es','en');
UPDATE "Entity" e SET content=replace(e.content, '[[lucy-lippard|Lucy Lippard]]', '[[_wave002-2bb9a92d7a020f5b|Lucy Lippard]]') WHERE e.id='cmtptpmip000ggxssoyqavhne';
UPDATE "EntityTranslation" t SET essay=replace(t.essay, '[[lucy-lippard|Lucy Lippard]]', '[[_wave002-2bb9a92d7a020f5b|Lucy Lippard]]') WHERE t."entityId"='cmtptpmip000ggxssoyqavhne';
UPDATE "Entity" e SET content=replace(e.content, '[[lucy-lippard|Lucy Lippard]]', '[[_wave002-2bb9a92d7a020f5b|Lucy Lippard]]') WHERE e.id='cmtptpmis000igxssmf1ps38f';
UPDATE "EntityTranslation" t SET essay=replace(t.essay, '[[lucy-lippard|Lucy Lippard]]', '[[_wave002-2bb9a92d7a020f5b|Lucy Lippard]]') WHERE t."entityId"='cmtptpmis000igxssmf1ps38f';

COMMIT;
